"""Discover published reports from tracking, catalogue and archive outputs."""
from pathlib import Path
import json,re,hashlib
R=Path(__file__).resolve().parents[1];catalogue=json.loads((R/'content/data/sites.json').read_text());tracked=json.loads((R/'.nift/tracked.json').read_text())['tracked'];entries=[]
notes={
 'cloudflare-docs':('Controlled 6-vCPU, 16GB no-swap host; exact provider unspecified','Aggregate cgroup peak bytes','Normal/targeted 1 and 5 pages, shared-template, no-change; original Astro production observations','Already exposed; retained correctness-failure and narrow validation caveats preserved'),
 'omarchy':('Original container platform unspecified; separate informal Intel NUC12 observation','Published process-tree Peak RSS; raw mechanism not retained locally','Container no-op and one page; informal NUC no-op','Container already exposed; historical NUC RSS unavailable: exact Nift executable and benchmark input binding unrecorded; no current-HEAD replacement'),
 'capgo':('Local i7-12700H / 20 CPUs / Ubuntu 26.04.1 / active desktop','GNU time maximum individual process RSS; maximum across three runs','No-op, docs, rich docs, marketing, blog; explicit targeted four families','Ordinary RSS added from existing exact three-run evidence; targeted RSS already exposed'),
 'docker':('Local i7-12700H / 20 CPUs / ~61GiB / active desktop','GNU time maximum individual process/phase RSS; median across five','1/10/100 pages, layout, navigation, metadata','Six case medians/ranges added from original sixty runs; no rerun'),
 'deno':('Local i7-12700H / 20 CPUs / active desktop','Maximum measured individual process/phase RSS','Unchanged, 1/10/100 bodies, layout, navigation, metadata, reference, add/rename/delete; upstream body','Original twenty single-case measurements plus five-run unchanged and upstream production phase maxima surfaced'),
 'ai-sdk':('Local i7-12700H / 20 CPUs / ~61GiB / active desktop','GNU maximum individual process/phase plus separate sampled ~50ms descendant RSS sum','Unchanged and thirteen changed-input cases per migration; thirteen upstream production cases','Original unchanged/upstream RSS exists; migration changed-input RSS requires supplemental pinned local reproduction and independent forced/restoration gates'),
 'temporal':('Local i7-12700H / 20 CPUs / ~61GiB / active desktop','Maximum individual process/phase plus separate sampled ~50ms descendant RSS sum','Unchanged, 1/10/100 bodies, metadata/layout/navigation/diagram/synced/search/island/add/rename/delete; two upstream edits','Original twenty-six cases and five-run unchanged surfaced, scopes separate; no rerun'),
 'website-generator':('Linode g6-standard-4 / us-east / Ubuntu24.04 / EPYC7601; targeted follow-up EPYC7542','Kernel waited-child high-water RSS, not aggregate tree RSS','No-op/leaf/shared-template at100/1000/10000; explicit target at each size','10k ordinary RSS already exposed; all sizes and targeted RSS added from retained five-run raw evidence; no new Linode'),
 'shell':('Linode g6-standard-4 / us-east / Ubuntu24.04; original campaign frozen per series','Kernel waited-child high-water RSS','Not applicable: process startup/RC and external invocation workloads','Incremental not applicable; existing memory belongs to invocation workloads'),
 'scripting':('Linode g6-standard-4 / us-east / Ubuntu24.04; original campaign frozen per series','Kernel waited-child high-water RSS','Not applicable: computation/structured-data invocation workloads','Incremental not applicable; no invented incremental site build'),
}
for t in tracked:
 name=t['name'];slug=name.strip('/').split('/')[-1]
 if not name.startswith(('sites/','benchmarks/')) or slug not in notes:continue
 site=next((x for x in catalogue if x['slug']==slug),{});source=R/'content'/name/'index.html';body=source.read_text();host,metric,cases,action=notes[slug]
 revisions=sorted(set(re.findall(r'(?<![a-zA-Z0-9])[0-9a-f]{40}(?![a-zA-Z0-9])',body)))
 if site.get('upstream_commit'):revisions.append(site['upstream_commit'])
 extra=R/'content/data/incremental-memory'/f'{slug}.json'
 provenance=json.loads(extra.read_text())['provenance'] if extra.exists() else {'upstream':site.get('upstream_commit'),'experiment_revision':'Unknown original capture binding; use stated published provenance rather than current HEAD'}
 if extra.exists():revisions+=re.findall(r'(?<![a-zA-Z0-9])[0-9a-f]{40}(?![a-zA-Z0-9])',extra.read_text())
 if slug in ['shell','scripting']:
  data=json.loads((R/'content/benchmarks/data/series.json').read_text())[slug];revisions.append(data['nift_revision'])
 entries.append({'report_url':'https://lab.nift.dev/'+name,'source':str(source.relative_to(R)),'template':t['template'],'repository':site.get('experiment_repo','https://github.com/nift-dev/'+('website-generator-benchmark' if slug=='website-generator' else slug+'-benchmark')),'original_platform':host,'pins':sorted(set(revisions)),'revision_context':provenance,'displayed_incremental_cases':cases,'timing_evidence':slug not in ['shell','scripting'],'memory_metric':metric,'action':action,'evidence':str(extra.relative_to(R)) if extra.exists() else 'Existing report and linked original evidence','status':'not applicable' if slug in ['shell','scripting'] else 'partial provenance gap' if slug=='omarchy' else 'awaiting supplemental gates' if slug=='ai-sdk' else 'complete'})
for slug in ['shell','scripting']:
 out=R/f'public/benchmarks/{slug}/series/20261008-v480/index.html';assert out.exists()
 identity=json.loads((__import__('evidence_sources').data_root('content/benchmarks/archives')/f'20261008-v480/{slug}/archive-identity.json').read_text())
 entries.append({'report_url':f'https://lab.nift.dev/benchmarks/{slug}/series/20261008-v480/','source':f'content/benchmarks/archives/20261008-v480/{slug}/index.html','template':'Frozen published standalone archive','repository':'https://github.com/nift-dev/'+slug+'-benchmark','original_platform':notes[slug][0],'pins':re.findall(r'[0-9a-f]{40}',json.dumps(identity)),'displayed_incremental_cases':'None; archived invocation benchmark','timing_evidence':False,'memory_metric':notes[slug][1],'action':'Incremental not applicable; archive identity/content preserved','evidence':f'content/benchmarks/archives/20261008-v480/{slug}/archive-identity.json','status':'not applicable'})
assert len(entries)==12
ai=__import__('evidence_sources').data_root('investigation/incremental-memory/ai-sdk')/'completion.json'
if ai.exists():
 complete=json.loads(ai.read_text())
 if complete.get('published_cases')==26 and complete.get('all_forced_equal') and complete.get('restoration_passed'):
  next(x for x in entries if '/sites/ai-sdk/' in x['report_url'])['status']='complete / supplemental local evidence'
for entry in entries:
 entry['incremental_applicability']='not applicable' if entry['status']=='not applicable' else 'applicable'
 entry['memory_evidence_status']='not applicable' if entry['status']=='not applicable' else 'original container evidence exists; historical NUC memory missing/unreproducible' if 'omarchy/' in entry['report_url'] else 'original unchanged/upstream plus supplemental migration memory' if 'ai-sdk/' in entry['report_url'] and entry['status'].startswith('complete') else 'original unchanged/upstream exists; migration changed-input supplement pending' if 'ai-sdk/' in entry['report_url'] else 'original exact-workload evidence exists'
out=Path(__import__('tempfile').mkdtemp(prefix='nift-labs-audit-'));ledger=out/'incremental-memory-audit.json';ledger.write_text(json.dumps({'discovery':'Current catalogue + tracked report routes + two published series archives; three index pages excluded as catalogues','reports':entries,'cloud_instances_created':0,'cloud_instances_deleted':0,'credentials_accessed':False},indent=2)+'\n')
md='# Labs incremental-memory audit\n\nScope discovered from catalogue JSON, tracked report routes, benchmark navigation and deployed archive HTML: **12 reports** (7 site reports, 3 current benchmark reports, 2 archived benchmark reports). Homepage, sites catalogue and benchmarks catalogue are navigation, not additional measurements.\n\n| Report | Original host | Incremental cases | Memory metric | Action/status | Evidence |\n|---|---|---|---|---|---|\n'
for x in entries:md+='| ['+x['report_url'].replace('https://lab.nift.dev/','')+']('+x['report_url']+') | '+x['original_platform']+' | '+x['displayed_incremental_cases']+' | '+x['memory_metric']+' | '+x['action']+' **'+x['status']+'** | '+x['evidence']+' |\n'
md+='\nThe companion JSON records source/template locations, repositories and all pinned revisions retained by each report/evidence snapshot. Unknown original provenance is explicitly unknown, not replaced with current HEAD.\n\n## Original-versus-supplemental boundaries\n\nNo accepted timing is changed. Docker and website-generator keep five-sample medians/ranges; Capgo keeps its maximum-across-three RSS convention. Deno/Temporal retain single changed-input observations. AI SDK migration memory is supplemental single-observation evidence at accepted implementation pins, on the original active NUC, with frozen Nift4.8.0 SHA `a77deda5ef4124886a6ad344cd0fe0a43a5fa02d793cdf7e7eef2ed19645d8c4`, Node24.21.0 and four authored workers. It is not the original timing cohort. Sampled resident-page sums stay separate from individual peaks.\n\n## Omarchy provenance limitation\n\nThe container five-run table already reports no-op/one-page memory. The separate informal NUC observation (0.085204s no-op,0.149989s full) has neither raw memory nor a frozen Nift executable identity/benchmark-input binding. The public repository has only initial commit `258581a9226264797ddddabf9fd20a8f66af0629`, no retained benchmark directory/history that recovers those missing fields; its documentation uses the old checked-path syntax. The Labs catalogue also lacks the upstream pin. No current-head/version run is relabeled as historical evidence. This observation remains explicitly unmeasured for RSS. Reproduction requires the original binary/command/context; do not fix architecture/bitrot in this audit.\n\n## Cloud and source safety\n\nNo Linode measurement is required: website-generator retained all incremental RSS, while shell/scripting and their archives have no incremental site-build workload. **Zero Linodes created/deleted; no cloud credential configuration accessed.** All migration working trees remain untouched. Supplemental AI SDK runs use disposable exports. No Nift implementation changes or optimizations.\n\n## Reporting convention\n\nWhen changed-input or incremental timing is published, capture and report peak memory for the same workload whenever technically meaningful. Preserve the exact memory metric and qualification. Full-build memory alone is not a substitute for iteration memory.\n'
(out/'incremental-memory-audit.md').write_text(md)
print('Audit preview written outside Labs:',out)
