#!/usr/bin/env python3
"""Generate the Deno report from retained, committed experiment evidence."""
from pathlib import Path
import json, statistics, html

R = Path(__file__).resolve().parents[1]
D = R / 'content/sites/deno/data'
def load(name): return json.loads((D/name).read_text())
def esc(value): return html.escape(str(value), quote=True)
def fmt(value, places=2): return f'{value:.{places}f}'
def pick(rows, model, case): return [r for r in rows if r['model']==model and r['case']==case]
def med(rows, key='whole_pipeline_s'): return statistics.median(r[key] for r in rows)
def component(rows, path):
    values=[]
    for row in rows:
        value=row['components']
        for key in path.split('.'): value=value[key]
        values.append(value)
    return statistics.median(values)
H='https://github.com/nift-experiments/deno/blob/7d663e4212d8f976b8ba0b29d819b9331db24522'
A='https://github.com/nift-experiments/deno-agent/blob/0b42efec8239f49214c821e32fe5f0cc8e389f15'
UP='https://github.com/denoland/docs/tree/9e5dd8d930c8734defe1c3172986e6312353ac1c'
rows=load('d9-final-profile-benchmark.json')
native=load('d9-final-upstream-benchmark.json')
life=load('d8-production-lifecycle.json')
initial=load('d7-initial-benchmark.json')
old=load('d8-profile-benchmark.json')
changed=load('d9-final-upstream-changed-input.json')
assert len(rows)==30 and len(native)==20 and len(life)==20
assert all(r['baseline_bytes_equal'] and r['files']==2573 for r in rows)
assert all(r['html_reference_equal'] and r['tracked_source_clean'] and r['files']==2573 for r in native)
assert all(r['incremental_equals_forced_full'] for r in life)
assert all(r['all_reference_bytes_equal'] and r['source_clean_after_build'] for r in load('d9-final-fresh-checkouts.json'))
assert load('d8-all-route-http.json')['equal_status_mime_and_body']
browser=load('d8-browser-parity.json')
assert browser['states']==104 and browser['pixel_identical_states']==3 and browser['control_region_only_differences']==101 and not browser['outside_control_differences']
assert all(r['outside_observed_control_regions_pixel_identical'] for r in browser['records'])
assert len(load('d8-browser-interactions.json'))==20 and all(r['pass'] for r in load('d8-browser-interactions.json'))
cases=[('warm-normal-publication','Unchanged cached publication'),('warm-forced-full','Forced full recomputation'),('application-cold','Fresh application state')]
expected={'deno':[1.31,13.16,11.16],'deno-agent':[.70,1.07,1.01]}
for model in expected:
    for (case,_),value in zip(cases,expected[model]):
        samples=pick(rows,model,case)
        assert len(samples)==5 and round(med(samples),2)==value
for case,value in [('warm-full',153.76),('application-cold',314.69),('prepared-input-warm-publication',25.57),('prepared-input-application-cold',159.58)]:
    samples=pick(native,'upstream',case)
    assert len(samples)==5 and round(med(samples),2)==value
for model,value in [('deno',134.86),('deno-agent',144.07)]:
    assert round(med(pick(initial,model,'warm-full')),2)==value
assert round(changed['whole_pipeline_s'],2)==135.08
assert round(load('d8-static-og-verification.json')['single_build_observation']['complete_s'],2)==23.35
for model,pair in [('deno',(16.51,16.70)),('deno-agent',(1.28,1.45))]:
    assert tuple(round(med(pick(old,model,case)),2) for case in ['warm-forced-full','application-cold'])==pair

def section(number, anchor, title, intro, body):
    return f'<section class="chapter" id="{anchor}" aria-labelledby="{anchor}-title"><p class="eyebrow">{number} / {anchor.replace("-"," ")}</p><h2 id="{anchor}-title">{title}</h2><p class="intro">{intro}</p>{body}</section>'
def link(url,label): return f'<a href="{esc(url)}">{esc(label)} ↗</a>'
def samples_cell(samples):
    values=[r['whole_pipeline_s'] for r in samples]
    return f'<td><strong>{fmt(med(samples))}s</strong><small>{fmt(min(values))}–{fmt(max(values))}s · 5 runs</small></td>'
def dual_table():
    s='<table class="dual"><caption>Migration publication · five serialized samples per model and mode · median and min–max range</caption><thead><tr><th scope="col">Mode</th><th scope="col">deno</th><th scope="col">deno-agent</th></tr></thead><tbody>'
    for case,label in cases:
        s+=f'<tr><th scope="row">{label}</th>'+''.join(samples_cell(pick(rows,m,case)) for m in ['deno','deno-agent'])+'</tr>'
    return s+'</tbody></table>'
def chart(title, caption, series, scale, unit='s'):
    s=f'<figure class="trace-chart"><figcaption><h3>{title}</h3><p>{caption}</p></figcaption><div class="axis" aria-hidden="true"><span>0</span><span>{scale/2:g}</span><span>{scale:g} {unit}</span></div>'
    for label,value,lo,hi,kind in series:
        places=1 if unit=='MiB' else 2
        s+=f'<div class="trace-row {kind}"><div class="trace-label"><span>{label}</span><strong>{fmt(value,places)} {unit}</strong></div><div class="rail" aria-hidden="true"><span class="bar" style="width:{value/scale*100:.4f}%"></span></div><p class="range">5 runs · {fmt(lo,places)}–{fmt(hi,places)} {unit}</p></div>'
    return s+'</figure>'
def series(samples, label, kind, memory=False):
    key=('maximum_measured_process_or_phase_rss_mib' if samples[0]['model']=='upstream' else 'maximum_measured_process_rss_mib') if memory else 'whole_pipeline_s'
    values=[r[key] for r in samples]
    return (label,statistics.median(values),min(values),max(values),kind)

parts=['''<header class="mast"><a class="brand" href="@path('/')"><i aria-hidden="true"></i>NIFT <span>LABS</span></a><nav aria-label="Report navigation"><a href="#parity">Parity</a><a href="#iteration">Edit loop</a><a href="#benchmarks">Build costs</a><a href="#maintenance">Maintenance</a><a href="#evidence">Evidence</a></nav><a class="back" href="@path('sites/')">All experiments ↗</a></header>
<main id="main" class="wrap">
<section class="hero" aria-labelledby="report-title"><div><p class="eyebrow">Experiment 05 / Deno Docs / October 2026</p><h1 id="report-title">Keep the source.<br><em>Shorten<br>the loop.</em></h1><p class="lede">A production documentation publication, reconstructed as two Nift projects. One keeps authoritative Markdown and structured references. The other maintains finished HTML.</p><p>Upstream is <a href="https://github.com/denoland/docs">denoland/docs</a>: Deno, Lume, Markdown/MDX, JSX, Prism and Tailwind. We pinned its source, preserved its production publication and compared two deliberately different maintenance contracts.</p><p class="independent">Independent Nift experiment. Not endorsed by Deno. Nift itself was not modified. This is a faithful migration, not an approximate redesign.</p></div><aside class="hero-art" aria-label="Pinned publication"><div class="orbit"><span class="node source">AUTHORITATIVE SOURCE</span><span class="node derive">DERIVE</span><span class="node compose">COMPOSE</span><span class="node publish">PUBLISH</span><strong>834</strong><span>HTML DOCUMENTS<br>ONE ACCEPTED PUBLICATION</span></div><div class="orb-foot"><span>UPSTREAM PIN</span><code>9e5dd8d930c8</code></div></aside></section>
<nav class="section-nav" aria-label="Reading order"><a href="#parity">01 / Prove the publication</a><a href="#architectures">02 / Choose the source</a><a href="#iteration">03 / Measure the loop</a><a href="#methodology">12 / Inspect the boundaries</a></nav>''']
parts.append(section('01','parity','The publication is the acceptance test.','Speed comes after the complete publication and behavior checks. Both migrations reproduce the frozen production reference.',
'''<div class="proof"><div><strong>2,573</strong><span>publication files</span></div><div><strong>834</strong><span>HTML documents</span></div><div><strong>481</strong><span>Markdown downloads</span></div><div><strong>834</strong><span>maintained OG images</span></div><div><strong>11,567</strong><span>local search records</span></div></div>
<div class="note"><strong>Fresh committed clones: every publication byte matches.</strong><p>Both final report-checkpoint clones began without application state, reproduced all 2,573 files by SHA-256 and left Git clean. Prepared dependencies and maintained inputs are explicitly outside that correctness observation.</p></div>
<div class="two"><div><h3>Routes, retrieval and retirement</h3><p>All 834 routes match status, MIME and HTML body hashes across the original and both models: 2,502 responses. Special HTTP checks cover redirects, Markdown content negotiation, health/404 behavior and cache headers.</p><p>Twenty production-default maintenance/lifecycle cases cover body edits, shared inputs, references and route add/rename/delete. <strong>Every changed publication equals forced recomputation</strong>, including ancillary output retirement.</p></div><div><h3>Browser parity, with differences retained</h3><p>The D8 recapture covers 104 model/theme/viewport states. Three screenshots exactly match corresponding D6 captures; 101 retain documented differences inside theme/search/copy-control regions. Every pixel outside those observed regions matches. The earlier D6 comparison also retains five tiny reference differences.</p><p>Twenty tab, copy, clipboard, search, mobile-navigation/TOC and tablet interactions pass separately. Bitmap dimensions and live CSS viewport/theme checks are recorded separately. <strong>This is not a claim that all screenshots are pixel-identical.</strong></p></div></div>
<p class="small">Search interaction fixtures exercise local two-hit, empty and error responses. They do not certify live Orama relevance/indexing. No upstream cloud upload, analytics or feedback was sent. Inherited duplicate IDs and potential unresolved links remain documented.</p>'''))
parts.append(section('02','architectures','Two sources. One publication.','The representations are intentionally different. The human path derives publication outputs; the agent-primary path maintains them.',
'''<div class="two"><article class="model"><p class="eyebrow">Nift deno / Authored-source / Human + agent</p><h3>Author the source. Derive the rest.</h3><ol class="pipeline"><li>Markdown/MDX, frontmatter + structured references <span class="state">AUTHORITATIVE</span></li><li>Corpus-bounded standalone renderer <span class="state derived">DERIVE</span></li><li>Transient verified HTML <span class="state cached">CACHE</span></li><li>Nift raw composition + explicit dependencies</li><li>Publication + search / LLM / download derivation</li></ol><p>Authored source organization, components and structured references remain editable. Generated HTML is disposable. Missing/corrupt cached outputs recover; source, renderer, metadata and toolchain changes invalidate verified derived work.</p></article><article class="model agent"><p class="eyebrow">Nift deno-agent / Rendered-source / Agent-primary</p><h3>Maintain the publication representations.</h3><ol class="pipeline"><li>HTML + explicit metadata/download/search/LLM projections <span class="state">AUTHORITATIVE</span></li><li>Nift raw composition + explicit dependencies</li><li>Publication</li></ol><p>No routine Markdown/MDX/JSX content renderer and no Deno runtime in normal publication. The smaller build trades derivation for coordinated source maintenance: the same edit may touch HTML, downloads, retrieval projections and metadata.</p></article></div>
<div class="note"><p>The renderer ports only behavior required by the pinned corpus; it does not reconstruct a general Lume framework. These are complete orchestrated pipelines, <strong>not native Nift <code>&#64;markup</code> performance measurements</strong>. OG images and compiled frontend assets are maintained publication inputs in both migrations.</p></div>'''))
changed_expected={'1-bodies':(4.48,1.72),'10-bodies':(4.91,2.29),'100-bodies':(5.61,1.71),'shared-layout':(2.03,1.75),'navigation':(15.55,1.80),'title-metadata':(17.75,1.66),'generated-reference-data':(14.88,1.56),'route-add':(16.80,1.69),'route-rename':(19.05,1.61),'route-delete':(19.69,1.93)}
labels=['1 body','10 bodies','100 bodies','Shared layout','Navigation','Title metadata','Generated reference data','Route add','Route rename','Route delete']
t='<table class="dual"><caption>Changed-input complete publication · one serialized observation per case/model, not five-run medians</caption><thead><tr><th scope="col">Changed input</th><th scope="col">deno</th><th scope="col">deno-agent</th></tr></thead><tbody>'
for (case,expected_pair),label in zip(changed_expected.items(),labels):
    values=[next(r['whole_pipeline_s'] for r in life if r['model']==m and r['case']==case) for m in ['deno','deno-agent']]
    assert tuple(round(v,2) for v in values)==expected_pair
    t+=f'<tr><th scope="row">{label}</th>'+''.join(f'<td><strong>{fmt(v)}s</strong></td>' for v in values)+'</tr>'
t+='</tbody></table>'
parts.append(section('03','iteration','The loop you repeat all day.','Developers and agents usually change a small part of a site. Iteration speed often matters more than cold full-build speed.',
'''<div class="spotlight"><div><strong>1.31s</strong><span>deno / unchanged publication median</span><p>Verified derived output and dependency-aware composition make a no-change publication inexpensive.</p></div><div><strong>4–6s</strong><span>deno / common body-edit observations</span><p>One, ten and one hundred authored-body edits complete in 4.48s, 4.91s and 5.61s. This shorthand describes those observations, not a latency guarantee.</p></div></div>
<p>A short feedback loop compounds over dozens or hundreds of edits: build, inspect, correct, repeat. These measurements cover publication until output exists. Source editing, coordinated agent projection updates, browser inspection and review are outside timed builds; end-to-end productivity was not measured.</p><div class="data-block">'''+t+'''</div>
<div class="note"><strong>Correctness travels with incremental speed.</strong><p>Dependency-aware rebuilds are a core architectural advantage, but stale route/download/search/alias retirement matters just as much. Every case above was compared with forced recomputation; corruption and metadata-removal probes provide additional checks.</p><p>Shared-source cases expose remaining costs: navigation, metadata and reference changes invalidate broadly; changed retrieval inputs trigger whole-index search preparation. Those slower rows remain visible.</p></div>
<p><strong>Upstream changed-input production observation: 135.08s total.</strong> This single observation repeats reference generation, search and full Lume production publication. It is <strong>not Lume development-server hot reload</strong>. Lume’s development-server latency was not measured and no claim is made about it.</p>'''))
warm_chart=chart('Warm publication: the prepared-input boundary','Linear scale, zero origin. Native uses prepared references; Nift models force their own complete publication. Asset/frontend ownership still differs.',
    [series(pick(native,'upstream','prepared-input-warm-publication'),'Native / prepared inputs','native'),series(pick(rows,'deno','warm-forced-full'),'deno / forced full','human'),series(pick(rows,'deno-agent','warm-forced-full'),'deno-agent / forced full','agent')],30)
nt='<table class="range-table"><caption>Qualified native production phases · five serialized samples per mode</caption><thead><tr><th scope="col">Workflow</th><th scope="col">Median</th><th scope="col">Range</th></tr></thead><tbody>'
for case,label in [('warm-full','Warm full'),('application-cold','Application-cold full'),('prepared-input-warm-publication','Prepared-input warm publication'),('prepared-input-application-cold','Prepared-input application-cold')]:
    s=pick(native,'upstream',case);vals=[r['whole_pipeline_s'] for r in s]
    nt+=f'<tr><th scope="row">{label}</th><td><strong>{fmt(med(s))}s</strong></td><td>{fmt(min(vals))}–{fmt(max(vals))}s</td></tr>'
nt+='</tbody></table>'
parts.append(section('04','benchmarks','Measure the work, not just the winner.','Cached publication, forced rendering and upstream reference generation are different workloads. Each boundary stays attached to its numbers.',
warm_chart+'<div class="data-block">'+dual_table()+'''</div><div class="note"><p><strong>Unchanged</strong> can reuse verified derived pages/exports. <strong>Forced full</strong> bypasses human caches and forces Nift composition. <strong>Fresh application state</strong> clears generated/output/build metadata while retaining committed inputs and installed dependencies. OS caches are uncontrolled; this is not a machine-cold test.</p><p>The final fresh human median being lower than forced warm is retained as observed. Active-host/runtime/OS variation is uncontrolled, not a demonstrated advantage of cold state.</p></div>
<h3>Upstream production workflow</h3>'''+nt+'''<p class="small">Frozen live std inputs; exact pinned WASM delivery. Compilation/startup remain measured. Full native includes reference type/doc regeneration → local search → Lume publication. Prepared-input native omits reference regeneration, matching the migration’s prepared-reference ownership more closely.</p>
<div class="note"><strong>Original official baseline: one observation, not a median.</strong><p>The original complete <code>deno task build</code> was <strong>171.56s / 3,117.1 MiB</strong>. It remains separate from the repeated campaign, whose live std acquisition and WASM delivery boundaries differ.</p><p>Native warm Lume already caches unchanged OG images by JSX. Native application-cold publication regenerates them. The migrations copy maintained images and frontend assets, so these are architecture comparisons, not identical transformation workloads.</p></div>'''))
history=f'''<div class="history"><article><p class="eyebrow">01 / Initial architecture</p><strong>134.86s / 144.07s</strong><p>Warm medians, deno / deno-agent. Both unnecessarily regenerated all 834 OG images during routine builds.</p><small>Historical five-run migration evidence retained.</small></article><article><p class="eyebrow">02 / Static-asset correction</p><strong>23.35s / 1.54s</strong><p>First corrected individual observations. Accepted image bytes became maintained assets, copied at their original public URLs.</p><small>Single observations, not medians.</small></article><article><p class="eyebrow">03 / Profiled architecture</p><strong>13.16s / 1.07s</strong><p>Final forced-full medians. Shared work, verified caches and persistent DOM workers reduce avoidable rendering cost.</p><small>Intermediate and earlier optimized campaigns stay separate.</small></article></div>'''
parts.append(section('05','image-correction','Stop rebuilding what you maintain.','The OG-image correction changed the benchmark architecture because it corrected the intended ownership model.',
history+'''<p>The initial routine regeneration was an implementation mistake. The finished site needs the accepted image bytes; the migrations maintain all 834 images under <code>assets/og/</code> and publish them at their original URLs. Regenerating an image after a page/title/template change is an <strong>explicit selected-image maintenance operation</strong>, not a hidden step in every build.</p><pre tabindex="0" aria-label="Explicit image maintenance"><code>python3 scripts/update-og.py --route /runtime/run/</code></pre>
<p>Upstream Lume’s image generation remains in its production pipeline and cold measurements. Moving generation into intentional source maintenance is not a claim that image updates are free; their diagnostic costs and unaffected-image checks are retained separately.</p>
<details><summary>Retained intermediate evidence and campaign variation</summary><p>The first optimized five-sample campaign measured deno forced/fresh at 16.51s / 16.70s and deno-agent at 1.28s / 1.45s. Final samples were collected after a small layout-removal correctness fix. That fix is not evidence of the later timing improvement: host, runtime and OS-cache variation remain uncontrolled. Both campaigns, intermediate cache evidence and the earlier human cold RSS outlier of 2,225.8 MiB remain recorded.</p></details>'''))
forced=pick(rows,'deno','warm-forced-full')
agent_forced=pick(rows,'deno-agent','warm-forced-full')
assert round(component(forced,'render_components.markdown_inclusive_s'),2)==.97
profile='<div class="profile">'
for label,path in [('Markdown + highlighting','markdown_inclusive_s'),('Shared layouts','layout_s'),('Grouped references','generators.reference/reference.page.ts'),('Derived search','search_s')]:
    value=component(forced,'render_components.'+path) if path!='search_s' and not path.startswith('generators.') else (statistics.median(r['components']['render_components']['generators']['reference/reference.page.ts'] for r in forced) if path.startswith('generators.') else component(forced,path))
    profile+=f'<div><strong>{fmt(value)}s</strong><span>{label}</span></div>'
profile+='</div>'
ct='<table class="dual stage-table"><caption>Forced-full component medians · nested subsets and parallel counters are not additive</caption><thead><tr><th scope="col">Stage</th><th scope="col">deno</th><th scope="col">deno-agent</th></tr></thead><tbody>'
for label,path in [('Renderer orchestration','render_s'),('Nift preparation + composition','nift_preparation_and_composition_s'),('Nift process (subset)','nift_process.wall_s'),('Local search + clock','search_s'),('LLM derivation','llms_s'),('Non-HTML publication','publication_s'),('Asset/ancillary copy (subset)','copy_subset_s'),('Static OG copy (subset)','copy_categories_subset_s.og_assets'),('Markdown-download copy (subset)','copy_categories_subset_s.markdown_downloads')]:
    v=fmt(component(forced,path),3);agent=fmt(component(agent_forced,path),3) if path in agent_forced[0]['components'] or path.startswith(('nift_process.','copy_categories_subset_s.')) else 'Maintained input'
    ct+=f'<tr><th scope="row">{label}</th><td>{v}s</td><td>{agent+("s" if agent!="Maintained input" else "")}</td></tr>'
ct+='</tbody></table>'
parts.append(section('06','profiling','The gap is not mostly Markdown.','The forced-full gap is 12.09s. Most of it comes from deriving a publication, but the chosen implementation is not an irreducible lower bound.',
profile+'''<p>deno derives bodies, JSX layouts, grouped references, downloads, search and LLM projections from authoritative source. deno-agent maintains those representations closer to publication form. Inclusive Markdown is about 0.97s; Prism is about 0.26s inside that figure. Only three pages use MDX.</p><p>Renderer orchestration is about 9.66s. DOM normalization accounts for 13.28s of <strong>summed parallel job work</strong>, overlapping producer/layout work; it is not another 13.28s to add to elapsed time. Independent component medians likewise do not sum exactly to a pipeline median.</p>'''+ct+'''
<details><summary>What profiling removed, and what remains</summary><p>Repeated component-directory inventories and shared metadata expansion were removed. Explicit input/output hashes allow reuse of deterministic pages and search/LLM exports. Four persistent DOM-only workers preserve the original parser, serializer and table wrapping; small edits avoid worker startup. There was no per-page MDX/JS subprocess to eliminate.</p><p>Cache corruption, missing ancillary outputs, metadata removal, layout removal against native Lume, aliases and literal template-like code were checked. Conservative shared-input invalidation remains. Search still uses a whole-stage key. Narrower invalidation, less shell/DOM work, lower prepared-reference memory and cheaper selected-image metadata preparation are future profiling targets.</p><p>The authoring model requires derivation, but not this exact DOM/layout implementation. There is no defensible claim that the entire remaining gap is unavoidable “Markdown tax”, or that it demonstrates a Nift core limit.</p></details>'''))
memseries=[series(pick(native,'upstream','warm-full'),'Native / warm full','native',True),series(forced,'deno / forced full','human',True),series(agent_forced,'deno-agent / forced full','agent',True),series(pick(rows,'deno','warm-normal-publication'),'deno / cached','human',True),series(pick(rows,'deno-agent','warm-normal-publication'),'deno-agent / cached','agent',True)]
assert [round(s[1],1) for s in memseries]==[3186.7,1486.5,132.3,104.3,30.8]
parts.append(section('07','memory','Less time, with a memory tradeoff.','Maximum measured process/phase RSS. These figures are not aggregate concurrent process-tree memory.',
chart('Measured process/phase memory','Median of five maxima per labelled workflow. Linear scale, zero origin; workload boundaries differ.',memseries,3500,'MiB')+'''
<p>Deno DOM workers are threads in the renderer process and contribute to its measured RSS. Diagnostic serial/two/four-worker runs were 22.36s / 887.1 MiB, 15.32s / 1,330.2 MiB and 13.51s / 1,485.8 MiB. They are tuning observations, not headline medians. Four workers favor elapsed time and consume more memory.</p><p>The final human forced range reaches 2,107.5 MiB; the earlier cold campaign reached 2,225.8 MiB. Those peaks remain visible. A faster human renderer is not a claim that runtime machinery has disappeared.</p>'''))
parts.append(section('08','maintenance','Build simplicity is not source simplicity.','The faster project has less transformation work. The more conventional source model has fewer publication representations to keep coherent.',
'''<div class="two"><article class="model"><p class="eyebrow">Nift deno / Authored-source / Human + agent</p><h3>Consistency from authoritative source</h3><ul class="list"><li>Markdown/MDX/frontmatter and structured API/reference inputs remain authoritative.</li><li>One source derives downloads, search and LLM projections.</li><li>Human-readable edits and diffs reduce opportunities for those outputs to drift.</li></ul><h3>Costs to own</h3><p>Renderer/layout/reference compatibility, derivation runtime, conservative shared-source invalidation and explicit prepared-input refresh tooling.</p></article><article class="model agent"><p class="eyebrow">Nift deno-agent / Rendered-source / Agent-primary</p><h3>A very small publication pipeline</h3><ul class="list"><li>About one second for measured forced/fresh publication.</li><li>No routine Markdown/MDX renderer or Deno content runtime.</li><li>Maintained HTML composes directly through Nift.</li></ul><h3>Costs to own</h3><p>Agents must keep HTML, Markdown downloads, search/LLM projections, metadata and navigation coherent. A body-hash acknowledgement detects an unacknowledged edit; it does not prove semantic consistency across representations.</p></article></div>
<p class="small">Coordinated source editing is outside timed publication. Lower build time is not a measured claim of lower total maintenance effort.</p>'''))
parts.append(section('09','assessment','Codex’s maintenance choice: Nift deno.','This corpus’s ancillary publication contract changes the judgment. Faster maintained HTML is useful, but source consistency matters more here.',
'''<p>Here, <strong>Nift <code>deno</code></strong> is the authored-source human+agent migration repository, <code>nift-experiments/deno</code>. <strong>Nift <code>deno-agent</code></strong> is the rendered-source agent-primary migration. <strong>Upstream Deno/Lume</strong> is the original implementation. The preference below is for the Nift authored-source migration.</p><p class="question">Does a 1.31s unchanged publication and a 4–6s common body-edit loop make the human-oriented source model cheap enough to prefer its stronger source consistency?</p>
<div class="verdict"><h3>Agents implement, humans direct</h3><p><strong>Preferred: Nift <code>deno</code> (authored-source migration)</strong></p><p>Yes, for this experiment. Common body edits already have a short feedback loop, while one authoritative source derives downloads, retrieval and LLM outputs. That consistency outweighs the additional build cost. Navigation/metadata/lifecycle edits are slower and remain part of the decision; neither those costs nor agent projection-editing effort is hidden.</p></div>
<div class="verdict"><h3>Humans and agents both edit</h3><p><strong>Preferred: Nift <code>deno</code> (authored-source migration)</strong></p><p>Markdown/frontmatter and structured inputs are easier to author and review. Editors do not manually synchronize the same fact across several maintained publication forms. The measured iteration loop makes that source model practical during routine work.</p></div>
<div class="verdict"><h3>Both already exist; migration effort removed → unchanged</h3><p>If migration effort and incumbency are removed, I still prefer the Nift authored-source <code>deno</code> implementation for both agent-led maintenance and mixed human+agent editing. The preference follows the ongoing source-of-truth contract and incremental feedback, not sunk migration effort or incumbency. Dropping/redesigning the ancillary requirements could change the agent choice, but would change this parity experiment.</p></div>'''))
parts.append(section('10','official-evaluation','Worth a serious engineering evaluation.','The agent believes the evidence justifies Deno evaluating an official migration from Lume to Nift. It does not establish that Deno definitely should migrate.',
'''<p>Full publication, common-edit iteration, measured memory and fresh reproducibility are strong enough to justify a scoped engineering evaluation. Keeping human-friendly authoritative source while publishing unchanged in about 1.3s and common body edits in 4–6s is a practical maintenance benefit, not just a cold-build graph.</p><p>An official decision must test real contributor edits and CI/deployment: adapter ownership, structured-input acquisition/refresh, frontend regeneration, Orama/search/backend/service boundaries, editor ergonomics and integration with Deno’s ecosystem. Broad invalidation and memory peaks remain useful targets. Performance alone does not certify production integration or establish universal superiority.</p>'''))
parts.append(section('11','init-review','The migration tooling was part of the experiment.','nift init --migration provided a useful operating framework. The corpus supplied the details it could not invent.',
'''<p>Initialization preserved existing AGENTS.md, supplied baseline-first/parity/checkpoint guidance and safely refused a rerun on an existing Nift project. The generated playbook was useful; AGENTS/HANDOVER alone were not a sufficient migration specification.</p><div class="two"><div><h3>Useful future scaffolds</h3><p>Baseline manifest; source-ownership table; dependency/cache inventory; divergence ledger; checkpoint/status table; distinct cached/forced/application-cold sample schemas.</p></div><div><h3>Guidance exposed by real work</h3><p>Metadata-removal tests; static assets versus generated products; projection coordination; remote-service boundaries; complete publication versus composition-only commands; non-destructive guidance refresh and source-model selection.</p></div></div><p>These are conceptual improvements for later tooling work, not Nift changes made during this migration or a general Lume implementation.</p>'''))
parts.append(section('12','methodology','Keep the qualifications in reading distance.','The host, retained inputs and external-service boundaries are part of the result.',
'''<dl class="method"><div><dt>Host and samples</dt><dd>Intel i7-12700H, 20 logical CPUs, 64 GiB RAM, Linux 7.0.0-29. Active desktop; OS caches/user workload uncontrolled. Five serialized samples per headline mode; alternating migration model order where practical. Medians and min–max ranges, not confidence intervals.</dd></div><div><dt>Tools and source</dt><dd>Nift 4.8.0 unchanged; Deno 2.9.7; pinned denoland/docs revision 9e5dd8d930c8734defe1c3172986e6312353ac1c. Measured migration code: deno 380baeb, deno-agent 4a81df5. Later report/closeout commits contain documentation/evidence only.</dd></div><div><dt>Prepared inputs</dt><dd>Dependency installation, acquisition, cloning and source editing excluded. Live std acquisition frozen. Prepared reference JSON/types/std and compiled frontend assets are maintained inputs, with explicit refresh ownership in both migrations.</dd></div><div><dt>Native WASM delivery</dt><dd>Repeated native timing locally delivers exact pinned resvg/esbuild WASM bytes. Original compilation count, worker lifecycle, startup and initialization remain inside timing. Two direct CLI fetch failures and three successful observations remain separate, not pooled. This is qualified production-phase timing, not an unchanged official full-task measurement.</dd></div><div><dt>Search and clocks</dt><dd>Human local search/LLM derivation remains measured; agent projections are maintained. Remote Orama relevance/upload/backend not certified. Frozen search/LLM/sitemap clocks are explicit parity inputs, not current production freshness timestamps.</dd></div><div><dt>Native non-HTML differences</dt><dd>Every native HTML document matches. Seven path/hash differences are classified: dependency-symlink realpaths change the SDK chunk filename/import while normalized code is identical; search/LLM/sitemap publication clocks differ. The migrations retain the original complete publication bytes.</dd></div><div><dt>Memory and counters</dt><dd>Maximum measured process/phase RSS, not simultaneous tree memory. Parsing/Prism/MDX are nested subsets. Parallel DOM/output job-work overlaps main-thread production; do not add it to elapsed wall time.</dd></div><div><dt>Validation limits</dt><dd>Documented browser control-state pixel differences are retained; separate interactions pass. Inherited unresolved paths/fragments and duplicate IDs are not silently repaired. Live external services, long-term editing productivity and Lume dev-server latency are unmeasured.</dd></div></dl>'''))
e='<div class="evidence"><article><p class="eyebrow">Human + agent / frozen closeout</p><h3>nift-experiments/deno</h3>'
for url,label in [('https://github.com/nift-experiments/deno','Repository'),(H+'/investigation/D9-COMPARISON.md','D9 final comparison'),(H+'/investigation/MIGRATION-INIT-FINAL-REVIEW.md','Final migration-init review'),(H+'/investigation/d9-final-profile-benchmark.json','Final migration samples'),(H+'/investigation/d9-final-upstream-benchmark.json','Qualified native samples'),(H+'/investigation/d8-production-lifecycle.json','Changed-input / lifecycle evidence'),(H+'/investigation/d8-browser-parity.json','Browser differences ledger'),(H+'/investigation/d9-final-fresh-checkouts.json','Fresh-checkout byte proof')]:e+=link(url,label)
e+='</article><article><p class="eyebrow">Agent-primary / reproduction</p><h3>nift-experiments/deno-agent</h3>'
for url,label in [('https://github.com/nift-experiments/deno-agent','Repository'),(A+'/README.md','Maintained-HTML build guide'),(A+'/investigation/D9-COMPARISON.md','Agent repository comparison'),(UP,'Pinned upstream source'),(H+'/investigation/d9-native-dependency-delivery.json','WASM delivery qualification'),(H+'/investigation/benchmark-runners/README.md','External benchmark runner instructions'),(H+'/investigation/d7-initial-benchmark.json','Preserved initial architecture samples'),(H+'/investigation/d8-profile-benchmark.json','Earlier optimized campaign')]:e+=link(url,label)
e+='</article></div>'
parts.append(section('13','evidence','Inspect the source. Reproduce the boundaries.','The migration repositories are unchanged by this Labs publication. Report numbers are generated from retained committed JSON snapshots.',
e+'''<h3>Complete publication commands</h3><p>From either migration checkout, prepare the pinned dependencies and maintained inputs described in its README before building.</p><pre tabindex="0" aria-label="Migration publication commands"><code>python3 scripts/build.py
python3 scripts/build.py --force
# Explicit selected-image maintenance, outside normal builds:
python3 scripts/update-og.py --route /runtime/run/</code></pre><p>Set the human project’s DENO_BIN and DENO_DIR as documented. <code>nift build</code> alone composes already-prepared fragments; it does not refresh compatibility-derived content. Application-cold reproduction clears ignored generated/output/build state, retaining maintained inputs and prepared dependencies. External benchmark runners need the documented sibling checkout/reference layout and new evidence directories.</p>'''))
parts.append('''<footer class="closing"><p class="eyebrow">Nift Labs / Independent experiment</p><h2>Keep the evidence.<br><em>Choose what to maintain.</em></h2><p>A fast publication is useful. A source model a team can keep coherent is the longer-term decision.</p><nav aria-label="Report footer"><a href="@path('sites/')">All experiments ↗</a><a href="@path('benchmarks/')">Benchmark collection ↗</a><a href="#main">Back to top ↑</a></nav></footer></main>''')
(R/'content/sites/deno/index.html').write_text('\n'.join(parts)+'\n')
(D/'report-summary.json').write_text(json.dumps({'migration_medians':expected,'source':'Retained D9 samples; generated and checked by scripts/render_deno.py','native_modes':{case:med(pick(native,'upstream',case)) for case in dict.fromkeys(r['case'] for r in native)},'changed_input_samples':20,'browser_states':104},indent=2)+'\n')
print('Deno report generated: headline/sample/parity/lifecycle/browser gates checked.')
