"""Generate the bounded TanStack report from pinned, SHA-verified evidence.

Only compact provenance/summary data and maintained HTML live in Labs. Acquisition
is an explicit maintenance operation; normal Nift builds never fetch evidence.
"""
from pathlib import Path
import json
import statistics
from html import escape
from evidence_sources import data_root, sources, url

ROOT = Path(__file__).resolve().parents[1]
PREFIX = 'content/sites/tanstack/data'
DATA = data_root(PREFIX)
def load(name): return json.loads((DATA / name).read_text())
summary = load('architecture-summary.json')
samples = load('architecture-samples.json')
components = load('components.json')
repro = load('reproduction.json')
snapshot = load('snapshot-rejection.json')
article = load('article-rejection.json')
history = load('historical-t10.json')
assert len(samples) == 80 and len(summary) == 16 and all(x['samples'] == 5 for x in summary)
assert len(history) == 45 and all(x['samples'] == 5 for x in history)
assert repro['expanded_browser']['states'] == 333 and repro['expanded_browser']['page_errors'] == 0
assert repro['equality']['normal_and_forced_equal_to_independent_fresh'] and repro['equality']['publication_files'] == 24224
assert snapshot['status'] == 'rejected-parity-loss' and not snapshot['timings_eligible']
assert article['status'] == 'rejected-as-authoritative-maintained-HTML-model' and not article['timing_eligible']
assert article['html_edit_visible_in_real_server_article'] and not article['html_edit_survives_hydration']
lookup = {(r['implementation'], r['workload']): r for r in summary}
for row in summary:
    cohort = [r for r in samples if (r['implementation'], r['workload']) == (row['implementation'], row['workload'])]
    assert len(cohort) == 5
    for metric in ('wall_seconds', 'maximum_individual_process_rss_kib', 'sampled_descendant_tree_peak_rss_kib'):
        assert row[metric] == {'median': statistics.median(r[metric] for r in cohort), 'min': min(r[metric] for r in cohort), 'max': max(r[metric] for r in cohort)}
MODELS = [('faithful-agent', 'A / faithful Start + Vite'), ('tanstack-agent', 'B / Start + Rsbuild')]
WORK = [('full', 'Warm full'), ('fresh', 'Fresh application state'), ('unchanged', 'Unchanged command'), ('body-1', 'One document'), ('shared-shell', 'Shared shell'), ('island', 'Browser component'), ('route-rename', 'Route rename'), ('route-delete', 'Route delete')]
assert lookup['faithful-agent', 'full']['wall_seconds']['median'] == 32.94
assert lookup['tanstack-agent', 'full']['wall_seconds']['median'] == 41.55
def evidence(name): return url(sources()['files'][PREFIX + '/' + name])
PIN = 'https://github.com/nift-experiments/tanstack-agent/blob/8bd68069410f984a5949e7fa0e629b6084c1caee/'
AUTH = 'https://github.com/nift-experiments/tanstack/tree/7af3af0141e09248dacfc11f722c495abadd96a4'
AGENT = 'https://github.com/nift-experiments/tanstack-agent/tree/8bd68069410f984a5949e7fa0e629b6084c1caee'
UPSTREAM = 'https://github.com/TanStack/tanstack.com/tree/862ccc3d191818320c3e6d217542883f80cb907a'
def table(head, rows):
    return '<div class="table-wrap" role="region" tabindex="0" aria-label="Measurements table; scroll horizontally on narrow screens"><table><thead><tr>' + ''.join('<th scope="col">'+h+'</th>' for h in head) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join('<th scope="row">'+str(c)+'</th>' if i == 0 else '<td>'+str(c)+'</td>' for i,c in enumerate(row))+'</tr>' for row in rows) + '</tbody></table></div>'
def val(row, metric='wall_seconds', mib=False):
    d=row[metric]; scale=1024 if mib else 1; precision=1 if mib else 2
    return f'<strong>{d["median"]/scale:,.{precision}f}</strong><small>{d["min"]/scale:,.{precision}f}–{d["max"]/scale:,.{precision}f}</small>'
def section(n, id, title, body):
    return f'<section class="chapter" id="{id}"><div class="chapter-label"><span>{n:02}</span><p>{id.replace("-"," ")}</p></div><div class="chapter-body"><h2>{title}</h2>{body}</div></section>'
def rails(title, metric, axis, unit, workloads, mib=False):
    out=f'<figure class="measurement"><figcaption>{title}</figcaption><div class="axis"><span>0</span><span>{axis/2:,.0f}</span><span>{axis:,.0f} {unit}</span></div>'
    for work,label in workloads:
        out+=f'<div class="trace-group"><h4>{label}</h4>'
        for impl,name in MODELS:
            d=lookup[impl,work][metric]; v=d['median']/(1024 if mib else 1); dp=1 if mib else 2
            out+=f'<div class="measure-line {"alternate" if impl=="tanstack-agent" else "faithful"}"><div class="measure-label"><span>{name}</span><b>{v:,.{dp}f} {unit}</b></div><div class="rail" aria-hidden="true"><i style="width:{100*v/axis:.4f}%"></i></div></div>'
        out+='</div>'
    return out+'</figure>'

parts=['''<header class="mast"><a class="brand" href="@path('/')">NIFT LABS<span>Case file / 08</span></a><nav aria-label="Report navigation"><a href="#boundary">Boundary</a><a href="#measurements">Measurements</a><a href="#rewrite">Next phase</a><a href="#evidence">Evidence</a></nav><a class="all" href="@path('sites/')">All experiments ↗</a></header><main id="main">
<section class="hero"><div class="hero-copy"><p class="eyebrow">Architecture investigation / 08 / October 2026</p><h1>TanStack.com<span>Migration<br>boundary</span></h1><p class="lead">Exploring where Nift fits alongside TanStack.<br>Not replacing the entire ecosystem.</p><p>We wanted Nift to own publication and build work while keeping the TanStack libraries and application behavior that make sense to retain. That boundary preserved the product, but did not produce a compelling migration.</p><p class="qualification">Independent research. No TanStack affiliation or endorsement. No Nift core changes.</p></div><figure class="boundary-console"><figcaption>Responsibility map / the boundary tested</figcaption><div class="console-domain publication-domain"><span class="domain-id">01 / NIFT-OWNED</span><h2>Publication</h2><div class="signal-wire"><i></i><i></i><i></i></div><p>Docs · projections · assets</p><strong>Prepared inputs / composition</strong></div><div class="console-boundary"><span>THE MIGRATION BOUNDARY</span><b aria-hidden="true">↯</b></div><div class="console-domain runtime-domain"><span class="domain-id">02 / RETAINED</span><h2>Application<br>runtime build</h2><div class="signal-wire"><i></i><i></i><i></i></div><p>Start · browser · Worker</p><strong>Dominant cost remains here</strong></div><div class="console-footer"><span>PUBLIC BEHAVIOR PRESERVED</span><span>OWNERSHIP STILL COUPLED</span></div></figure><aside class="finding" aria-label="Current experiment status"><p class="eyebrow">Disposition / current phase</p><div class="status-block"><span>Migration result</span><strong>No compelling <br>migration found</strong><p>Unsuccessful / poor architectural fit</p></div><div class="status-block next"><span>Next phase</span><strong>Rewrite experiment <br>planned</strong><p>Not started. Success is not assumed.</p></div><div class="boundary-mark" aria-hidden="true"><span>NIFT-OWNED</span><i></i><span>RETAINED RUNTIME</span></div></aside></section>
<div class="finding-line"><span>Finding 01</span><p>The retained Start/backend build remained dominant outside the work Nift was replacing.</p></div>''']
parts.append(section(1,'boundary','Move the boundary. Keep the product.','''<p>The target was the full public application, not a static imitation of its docs. Request-specific sessions, Router/Query behavior, real charts, search, chat/API boundaries and generated products remained part of the contract.</p><figure class="architecture-map"><figcaption>Build responsibility and request-time ownership</figcaption><div class="architecture-columns"><div class="architecture-path"><h3>Upstream</h3><p>Original content inputs</p><span class="connector" aria-hidden="true">↓</span><p>TanStack Start / Vite</p><span class="connector" aria-hidden="true">↓</span><p>React / Redact / Router / Query<br>Cloudflare application services</p><strong>Start owns request-time HTML</strong></div><div class="architecture-path"><h3>A / faithful Nift</h3><p class="nift-node">Nift publication<br>Docs + projections + assets</p><span class="connector" aria-hidden="true">↓</span><p>Retained Start / Vite build</p><span class="connector" aria-hidden="true">↓</span><p>Original browser + Worker runtime</p><strong>Dominant build cost remains</strong></div><div class="architecture-path"><h3>B / alternate engine</h3><p class="nift-node">Same Nift publication</p><span class="connector" aria-hidden="true">↓</span><p>Official Start / Rsbuild adapter</p><span class="connector" aria-hidden="true">↓</span><p>Original browser + Worker runtime</p><strong>Lower RSS / slower warm full</strong></div></div><p class="figure-note">B changes the compiler engine. It does not transfer request-time page or docs rendering to Nift.</p></figure><div class="source-models"><div><h3>Nift <code>tanstack</code><small>Authored-source / faithful</small></h3><p>Maintained Markdown, frontmatter and structured references derive document AST, raw/download views and metadata. Nift composes prepared inputs; Start renders the public application.</p></div><div><h3>Nift <code>tanstack-agent</code><small>Rendered-source / agent-primary</small></h3><p>Maintained TanStack document AST envelopes with explicit original/download projections. This is a hybrid runtime-consumed representation, <strong>not whole maintained HTML</strong>. More restructuring freedom did not relax parity.</p></div></div><p>React, Router, Query, Table and AI remain product dependencies where used. Start also supplies server functions, serialization and hydration. Vite is build tooling, not a required runtime library. Redact aliases, Tailwind, Content Collections, Sentry runtime and Cloudflare bindings remain explicit integration responsibilities.</p>'''))
parts.append(section(2,'paths','Five branches. No forced winner.','''<ol class="branches"><li class="accepted"><span class="branch-code">A</span><div><h3>Faithful Start / Vite</h3><p>Accepted behavior. Preserved as the conservative default, but not compelling as a complete application migration.</p></div><span class="path-state">Preserved</span></li><li class="investigated"><span class="branch-code">B</span><div><h3>Official Start / Rsbuild adapter</h3><p>Executable alternate engine. Memory falls; warm full publication slows. Start stays in charge of SSR.</p></div><span class="path-state">Tradeoff</span></li><li class="terminated"><span class="branch-code">C1</span><div><h3>Whole-page snapshot + real backend</h3><p>Required request-specific session behavior is frozen in the published HTML.</p></div><span class="path-state">Rejected</span></li><li class="terminated"><span class="branch-code">C2</span><div><h3>Maintained article HTML bridge</h3><p>HTML-only edits appear on the server, then disappear when the original AST-based components mount.</p></div><span class="path-state">Rejected</span></li><li class="planned"><span class="branch-code">→</span><div><h3>Rewrite from first principles</h3><p>A different design question, with explicit publication, island and service boundaries.</p></div><span class="path-state">Planned</span></li></ol><p class="qualification">Plain esbuild also failed with 204 browser-graph compilation errors: server-only imports and framework transformations cannot simply be skipped. Failed compilation and rejected C branches receive no successful-build timing.</p>'''))
parts.append(section(3,'parity','The migration failure was architectural.','''<p class="lead">Preserving behavior worked. Finding a worthwhile new ownership boundary did not.</p><div class="proof-strip"><div><strong>7,527</strong><span>document contracts / 25 roots</span></div><div><strong>333</strong><span>browser states / no page errors</span></div><div><strong>24,224</strong><span>files / normal–forced byte equality</span></div></div><p>The Rsbuild candidate reproduced with independently installed frozen runtime dependencies and a separately locked adapter toolchain. All 244 maintained static assets match byte-for-byte. Required type, lint, unit, chat and desktop suites pass, with one existing desktop skip.</p><p>Real local Worker proofs preserve API boundaries, generated output, byte-identical request-time OG PNGs, fresh sessions, Markdown negotiation, mobile navigation, search navigation and the catalog renderer. No handler was replaced with a static success stub.</p><p class="qualification">Browser semantics and interaction checks are not universal pixel identity. API/service proofs use controlled fixtures and unauthenticated boundaries; private live authenticated integrations are not certified. Hosted Algolia remains; there is no omitted local search-index build.</p>'''))
hist={(r['implementation'],r['workload']):r for r in history}
parts.append(section(4,'earlier-result','Keep the first faithful result visible.','''<p>The preserved T10 campaign has 225 observations: 15 cases × three implementations × five samples. It predates the T11 cache work and the T12 architecture comparison below. These cohorts must not be spliced into a single ranking.</p>'''+table(['T10 / seconds, median [min–max]','Upstream Start / Vite','Nift authored-source','Nift rendered-source'],[[label]+[val(hist[m,w]) for m in ['upstream','tanstack','tanstack-agent']] for w,label in [('full','Warm full'),('fresh','Fresh application state'),('unchanged','Unchanged command'),('body-1','One document'),('route-rename','Route rename'),('route-delete','Route delete')]])+'''<p>Unchanged and rename/delete publication improved; ordinary upstream document edits remained competitive or faster. Upstream changed-doc timing is its native ready-input R2 refresh, whereas Nift measures complete document/assets publication. This is production work, not development-server/HMR latency. Fresh-state cleanup placement also differs; the original report keeps those boundaries visible.</p><p class="qualification">The T11 replacement 225-row campaign is still pending. Its optimized authored timings are not inferred from the agent-only T12 results.</p>'''))
parts.append(section(5,'measurements','Less memory. More time. Still Start.','''<p>The bounded T12 investigation compares two <strong>agent-source</strong> pipelines: faithful Start/Vite and official Start/Rsbuild. It is not a comparison of authored versus rendered source.</p><div class="tradeoff">'''+rails('Warm full / complete publication','wall_seconds',50,'s',[('full','Time')])+rails('Warm full / maximum individual process RSS','maximum_individual_process_rss_kib',5000,'MiB',[('full','Memory')],True)+'''</div><p class="tradeoff-caption">Rsbuild saves memory here, but loses warm-full time. Neither removes the dominant runtime build. This is the observed tradeoff in this application, not a judgement about Rsbuild generally.</p>'''+table(['T12 / seconds, median [min–max]']+[n for _,n in MODELS],[[label]+[val(lookup[m,w]) for m,_ in MODELS] for w,label in WORK])+'''<p class="qualification">80 accepted samples: eight workloads × two variants × five serialized repetitions. Clock includes required browser <strong>and</strong> backend bundling, content, assets and Worker configuration. No separate service build is hidden. Fresh-state ranges overlap substantially; no fresh-build winner is claimed. Installed dependencies and acquisition are excluded; fresh application state does not mean cold OS caches. Fixed cohort order and shared-host load limit small-difference claims.</p>'''))
parts.append(section(6,'incremental-memory','The boundary is visible in iteration memory.','''<p>Document-only edits and lifecycle updates reuse verified runtime bundles. Shared shell and browser-component edits cross the retained compiler boundary. Peak memory rises with that boundary, not with Nift simply rendering one page.</p>'''+rails('Changed-input / maximum individual process RSS','maximum_individual_process_rss_kib',5000,'MiB',WORK[2:],True)+table(['T12 / MiB, median [min–max]','A individual process','B individual process','A sampled tree','B sampled tree'],[[label]+[val(lookup[m,w],metric,True) for metric in ['maximum_individual_process_rss_kib','sampled_descendant_tree_peak_rss_kib'] for m,_ in MODELS] for w,label in WORK])+'''<p class="qualification">Individual RSS is GNU time maximum process/phase usage, not aggregate memory. Tree RSS is a nominal 50ms PID-deduplicated descendant sum: it can miss short peaks and double-count shared mappings. It is not PSS. Both scopes and observed ranges remain separate; neither is a dedicated-machine memory guarantee.</p>'''))
fullcomp={r['implementation']:r['median_seconds'] for r in components if r['workload']=='full'}
parts.append(section(7,'dominant-cost','Nift did not consume 4.4 GiB to render pages.','''<div class="ownership-layers"><div class="owned-layer"><span>Nift-owned work</span><h3>Prepared docs / projections / composition</h3><p>Useful publication work. Not the dominant full-build cost.</p></div><div class="boundary-seam"><span>Migration boundary</span></div><div class="retained-layer"><span>Retained application compiler</span><h3>Start + browser/server emission</h3><p>Expensive runtime build responsibility remains here.</p></div></div>'''+table(['Warm full component / median seconds','A / Start + Vite','B / Start + Rsbuild'],[[name]+[f'{fullcomp[m][key if m=="faithful-agent" or key!="retained_vite_build" else "retained_rsbuild_build"]:.2f}' for m,_ in MODELS] for key,name in [('retained_vite_build','Retained engine, both environments'),('content_publication','Complete content stage'),('nift_composition','Nift composition within content stage'),('retained_asset_publication','Retained asset publication'),('publisher_compilation','Publisher compilation')]])+'''<p>Vite's approximately 4.4 GiB process peak occurs around server emission. V8 live heap was much smaller at the sampled RSS peak, and heap caps did not materially remove that RSS peak. This does not establish a native allocator cause; overlapping diagnostic heap trials are not accepted timing comparisons. Rsbuild's own Node compiler becomes dominant around SSR completion.</p><blockquote>This does not show that Nift itself has the same build cost or memory profile as TanStack Start. It shows that the migration retained too much of the existing runtime/build architecture for Nift to meaningfully change the dominant cost.</blockquote><p class="qualification">Nift composition is a nested component, not an additional cost to sum on top of content publication. Median components need not sum to a median total. These are complete orchestrated pipelines, not native <code>@markup</code> performance.</p>'''))
parts.append(section(8,'rejected-splits','The deeper branches ended at real contracts.','''<div class="rejection"><span class="termination" aria-hidden="true">×</span><div><p class="eyebrow">C1 / branch terminated</p><h3>A live backend cannot unfreeze a static shell.</h3><p>Original backend forwarding worked and its request seed rotated. The Nift-published whole page retained the old seed. Required partner/session behavior therefore failed. Static output alone was not a faithful substitute.</p></div></div><div class="rejection"><span class="termination" aria-hidden="true">×</span><div><p class="eyebrow">C2 / branch terminated</p><h3>Server-visible HTML was not the maintained authority.</h3><p>Three real pages covered ordinary content, a table and tabs/code. Twelve scoped browser states initially matched. An HTML-only edit published normally and appeared in SSR, then vanished after the original interactive components mounted from their unchanged AST. A shadow AST would require coordinated maintenance; a clean HTML authority needs a different component/island boundary.</p></div></div><p>We stopped rather than weaken parity, fake dynamic functionality or reimplement substantial parts of Start. These bounded failures do not prove that every possible service/island design is impossible.</p>'''))
parts.append(section(9,'what-worked','Useful work. An unconvincing migration.','''<ul class="findings-list"><li><strong>Verified bundle reuse</strong><span>Unchanged publication avoids redundant application compilation.</span></li><li><strong>Docs stay outside the heavy build</strong><span>Normal document edits reuse the unchanged browser/backend bundles.</span></li><li><strong>Correct publication and retirement</strong><span>Custom publisher, explicit dependencies, rename/delete handling and cache repair preserve outputs.</span></li><li><strong>Independent recomputation</strong><span>Normal and forced output equality survives a fresh dependency install.</span></li></ul><p>Those gains matter, but they do not make the entire application migration worthwhile. Full/fresh build cost, retained peak memory and compiler integration complexity remain. The source cache improvements do not transfer request-time HTML ownership.</p><h3>Why publish a negative result?</h3><p>Labs records what actually happens, including targets where migration is not compelling. Publishing the failed boundary makes the successful experiments more credible and keeps architecture fit separate from benchmark cherry-picking.</p>'''))
parts.append(section(10,'rewrite','A new question. Not a promised rescue.','''<div class="rewrite-plan"><div class="rewrite-state"><span>Current</span><strong>Migration boundary<br>exhausted</strong></div><span class="rewrite-arrow" aria-hidden="true">→</span><div class="rewrite-state future"><span>Next / planned</span><strong><code>nift init --rewrite</code></strong></div></div><p class="lead">If TanStack.com were designed around Nift from the start, could it retain its public design and useful TanStack functionality with a better build and maintenance model?</p><p>The next phase, when resources allow, is a clean rewrite. Nift could own publication and composition; React and TanStack Router/Query/Table/AI could remain where useful; API, auth, chat and database work could have explicit service boundaries. Start would stay only if it earns its role. Lighter bundling and simpler source/projection ownership would be design choices, not assumptions.</p><h3>What would count as a compelling rewrite?</h3><ul class="criteria"><li>Same or very close public design and UX</li><li>Preserved important interactive behavior and useful TanStack libraries</li><li>Substantially lower full-build peak memory</li><li>Materially faster fresh/full publication, cheap unchanged and incremental work</li><li>A simpler maintenance model</li><li>Agent preference for the rewrite in at least one maintenance scenario</li></ul><p>The migration already dogfooded <code>nift init --migration</code>. The rewrite will test whether <code>nift init --rewrite</code> helps agents make larger architectural decisions instead of inheriting incumbent constraints. No rewrite has started and no success is guaranteed. Its services, complete costs and remaining weaknesses will need their own evidence.</p>'''))
links=[('Pinned upstream application',UPSTREAM),('Nift tanstack / authored-source repository',AUTH),('Nift tanstack-agent / rendered-source repository',AGENT),('T12 architectural ownership report',PIN+'investigation/T12-ARCHITECTURE.md'),('T12 raw 80-sample dataset',evidence('architecture-samples.json')),('T12 summaries and ranges',evidence('architecture-summary.json')),('Component costs',evidence('components.json')),('Independent reproduction receipt',evidence('reproduction.json')),('Whole-page rejection',evidence('snapshot-rejection.json')),('HTML authority rejection',evidence('article-rejection.json')),('Preserved T10 / 225-row summary',evidence('historical-t10.json')),('Original T10 intermediate report',PIN+'INTERMEDIATE-REPORT.md'),('Heap/cache optimization qualifications',PIN+'investigation/T11-OPTIMIZATION.md'),('Prototype code and dependency inventory',PIN.replace('/blob/','/tree/')+'investigation/t12-prototypes')]
parts.append(section(11,'evidence','Inspect the result. Keep the boundaries.','''<p>This page closes the <strong>bounded migration architecture phase</strong> as unsuccessful. It uses the accepted T12 investigation and keeps T10 historical evidence separate. The broader T11 replacement 225-row campaign is not complete and is not used to overstate the conclusion. Repository checkpoints were clean and synchronized at publication; frozen links preserve the exact source/evidence state.</p><p>Toolchain: Nift 4.9.0, Node 25.9.0 and pnpm 11.1.0. Raw logs, environment/sampler records, restoration receipts and rejected experiments remain in the experiment repositories. Labs stores compact rendering summaries and displayed assets only.</p><ul class="evidence-links">'''+''.join(f'<li><a href="{escape(href)}">{escape(label)} <span aria-hidden="true">↗</span></a></li>' for label,href in links)+'''</ul>'''))
parts.append(section(12,'conclusion','Do not migrate using this architecture.','''<p class="lead">We would not recommend migrating TanStack.com to Nift using the architecture tested here.</p><p>The retained runtime/backend build dominates, and the migration does not produce enough performance or memory benefit to justify the complexity. For both agent-led maintenance and mixed human/agent editing, the current assessment favors the original application architecture; among the two Nift migrations, the authored source has the stronger source-of-truth model.</p><p>A rewrite remains worth testing because it removes the inherited architectural constraint and asks a different question. If the benefits do not appear, that result belongs here too.</p><div class="closing-status"><span>Migration: unsuccessful / poor fit</span><span>Rewrite: planned</span></div>'''))
parts.append('</main><footer class="footer"><a href="@path(\'/\')">Nift Labs</a><p>Preserve parity. Measure honestly. Publish the boundary.</p><a href="@path(\'sites/\')">Explore the experiments ↗</a></footer>')
destination=ROOT/'content/sites/tanstack/index.html'
destination.write_text('\n'.join(parts)+'\n')
compact={'cohort':'T12 bounded agent-source architecture comparison','source':sources()['files'][PREFIX+'/architecture-summary.json'],'summary':summary,'components':components,'scope':'Both browser and backend costs included when rebuilding; nominal 50ms sampled tree is separate from maximum individual process RSS.'}
(ROOT/'content/sites/tanstack/summary.json').write_text(json.dumps(compact,separators=(',',':'))+'\n')
print('Rendered TanStack report: 80 T12 samples, separate historical T10, qualified memory and rejected branches.')
