#!/usr/bin/env python3
"""Render the Labs article from frozen A10 observations; reject changed headlines."""
from pathlib import Path
import json,statistics,html,hashlib
R=Path(__file__).resolve().parents[1];D=__import__('evidence_sources').data_root('content/sites/ai-sdk/data')
for name,sha in json.loads((D/'provenance.json').read_text())['snapshots'].items():assert hashlib.sha256((D/name).read_bytes()).hexdigest()==sha, name
def load(n):return json.loads((D/n).read_text())
def esc(v):return html.escape(str(v),quote=True)
def med(v):return statistics.median(v)
models=['upstream','ai-sdk','ai-sdk-agent'];labels=['Upstream Next.js/Geistdocs','Nift ai-sdk (authored-source)','Nift ai-sdk-agent (rendered-source)'];kinds=['upstream','authored','rendered'];modes=['warm-full','fresh-application-state','unchanged-cached'];mode_labels=['Warm full','Fresh application','Unchanged command']
rows=load('samples.json');assert len(rows)==45 and all(x['exit_code']==0 for x in rows)
def pick(model,mode):return [x for x in rows if x['project']==model and x['mode']==mode]
def values(model,mode,key='elapsed_s',div=1):return [x[key]/div for x in pick(model,mode)]
expected=[[337.34,306.03,264.93],[83.16,68.87,12.87],[37.96,28.09,8.43]]
for model,target in zip(models,expected):
 for mode,e in zip(modes,target):assert len(pick(model,mode))==5 and round(med(values(model,mode)),2)==e
for model,e in zip(models,[23671.5,901.8,758.9]):assert round(med(values(model,'warm-full','maximum_process_phase_rss_kib',1024)),1)==e
for model in ['authored','rendered']:
 browser=load(model+'-A9-BROWSER-MATRIX.json');assert len(browser)==72 and all(x['pass'] and not x['differences'] for x in browser)
 fresh=load(model+'-A9-FRESH-CLONE-PROOF.json');assert fresh['fresh_clone_publication_byte_equal'] and fresh['clean_after_build'] and fresh['public_runtime_files']==3219
 proof=load(model+'-A10-CLOSEOUT-PROOF.json');assert proof['publication_matches_accepted_fresh_clone'] and proof['report_links_resolve']
u=load('upstream-changed.json');h=load('authored-body.json')+load('authored-routes.json');a=load('rendered-body.json')+load('rendered-routes.json');c=load('rendered-coordinated.json');assert len(u)==len(h)==len(a)==13 and all(x['incremental_forced_equal'] for x in h+a+c)
co={'metadata-update-remove':'metadata-coordinated','historical-version':'historical-version-coordinated','provider-reference':'provider-reference-coordinated'}
expected_changes=[(267.89,13.19,7.83),(299.09,14.61,7.94),(317.16,20.95,8.28),(321.72,15.56,10.50),(326.63,20.18,15.15),(333.14,15.99,9.84),(304.79,14.24,7.48),(266.53,16.34,8.68),(271.14,12.23,5.90),(259.37,19.31,11.77),(256.71,21.32,11.92),(231.23,24.36,11.06),(248.95,21.71,10.63)]
H='https://github.com/nift-experiments/ai-sdk/blob/6d07d2f06a96d33deac0384514574d069cce98b7';A='https://github.com/nift-experiments/ai-sdk-agent/blob/524b1840a0a36d0dafdfbc368f52fb526951bad8';UP='https://github.com/vercel/ai/tree/3ebefff610f96892c50be48cf1838c453e2349f7'
def link(url,text):return f'<a href="{esc(url)}">{esc(text)} <span aria-hidden="true">↗</span></a>'
def section(n,id,title,lead,body):return f'<section class="chapter" id="{id}" aria-labelledby="{id}-title"><div class="chapter-head"><p class="eyebrow">{n:02} / {id}</p><h2 id="{id}-title">{title}</h2><p class="lead">{lead}</p></div>{body}</section>'
def chart(title,caption,mode='warm-full',key='elapsed_s',div=1,axis=400,unit='s'):
 s=f'<figure class="chart"><figcaption><h3>{title}</h3><p>{caption}</p></figcaption><div class="axis" aria-hidden="true"><span>0</span><span>{axis/2:g}</span><span>{axis:g} {unit}</span></div>'
 for model,label,kind in zip(models,labels,kinds):
  v=values(model,mode,key,div);digits=1 if unit=='MiB' else 2
  s+=f'<div class="signal {kind}"><div class="signal-label"><span>{label}</span><strong>{med(v):,.{digits}f}<small> {unit}</small></strong></div><div class="rail" aria-hidden="true"><i style="width:{med(v)/axis*100:.4f}%"></i></div><p class="range">{min(v):,.{digits}f}–{max(v):,.{digits}f} {unit} · five runs</p></div>'
 return s+'</figure>'
parts=['''<header class="mast"><a class="brand" href="@path('/')">NIFT <span>LABS</span><i aria-hidden="true"></i></a><nav aria-label="Report navigation"><a href="#parity">Parity</a><a href="#islands">Islands</a><a href="#benchmarks">Builds</a><a href="#iteration">Iteration</a><a href="#opinion">Judgement</a></nav><a href="@path('sites/')">All experiments ↗</a></header>
<main id="main" class="wrap"><section class="hero" aria-labelledby="report-title"><div class="hero-copy"><p class="eyebrow">Experiment 06 / AI SDK docs / October 2026</p><h1 id="report-title">Keep the islands.<br><em>Change<br>the build.</em></h1><p class="lede">Three production workflows. Two maintained source models. The interactive React parts stay.</p><p>Vercel’s AI SDK documentation, faithfully migrated to Nift composition around retained framework islands. We preserve the publication first, profile the expensive work, and compare complete production pipelines.</p><p class="independent">An independent Nift Labs experiment. Not endorsed by Vercel. No Nift core or migration templates were changed.</p></div>
<aside class="graph" aria-label="Static content graph with independently hydrated React islands"><div class="graph-top"><span>PUBLICATION GRAPH</span><span>STATIC + INTERACTIVE</span></div><svg viewBox="0 0 440 390" role="img" aria-label="Static article nodes connect through Nift composition; highlighted React islands hydrate around that content"><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#30332c" stroke-width=".6"/></pattern></defs><rect width="440" height="390" fill="url(#grid)"/><g fill="none" stroke="#656b58" stroke-width="1.5"><path d="M66 88H220V185H374M66 185H374M66 290H220V185M220 290H374V185M110 185V340M330 88V185"/></g><g fill="#101110" stroke="#828975"><rect x="42" y="64" width="48" height="48"/><rect x="42" y="161" width="48" height="48"/><rect x="42" y="266" width="48" height="48"/><rect x="306" y="64" width="48" height="48"/><rect x="350" y="266" width="48" height="48"/></g><g fill="#c9ff52"><rect x="197" y="162" width="46" height="46"/><rect x="350" y="161" width="48" height="48"/><rect x="197" y="266" width="46" height="46"/></g><g fill="#101110" font-size="11" font-family="monospace" text-anchor="middle"><text x="220" y="182">NIFT</text><text x="220" y="196">COMPOSE</text><text x="374" y="189">REACT</text><text x="220" y="294">REACT</text></g><g fill="#e8eddf" font-size="10" font-family="monospace"><text x="40" y="49">AUTHORED / RENDERED</text><text x="283" y="49">STATIC CONTENT</text><text x="126" y="348">OPAQUE HTML + HYDRATION</text></g><circle cx="110" cy="340" r="4" fill="#c9ff52"/></svg><div class="graph-foot"><strong>1,674</strong><span>HTML ROUTES<br>ONE ACCEPTED TARGET</span></div></aside></section>
<nav class="reading" aria-label="Reading order"><a href="#architectures">01 / Source models</a><a href="#parity">02 / Prove the site</a><a href="#benchmarks">04 / Measure publication</a><a href="#methodology">13 / Inspect boundaries</a></nav>''']
parts.append(section(1,'architectures','Name the three workflows.','The repo names describe maintained source models. Neither Nift repository is the upstream AI SDK application.',f'''<div class="models"><article class="model upstream"><p class="eyebrow">UPSTREAM</p><h3>Vercel AI SDK docs<br>Next.js / Geistdocs</h3><p>Original authored content, version synchronization, Fumadocs and the Next production application.</p><ol><li>Markdown/MDX + structured inputs</li><li>Version synchronization + source modules</li><li>Next compile / rendering / publication</li></ol><p>{link(UP,'Pinned vercel/ai source')}</p></article><article class="model authored"><p class="eyebrow">NIFT / AUTHORED-SOURCE</p><h3>Nift <code>ai-sdk</code><br>(authored-source)</h3><p>Maintained Markdown/MDX/frontmatter and structured/versioned sources. Downloads, search and LLM references derive from that authority.</p><ol><li>Authored source + local pinned versions</li><li>Bounded renderer → transient HTML</li><li>Nift composition + retained islands</li><li>Publication + derived projections</li></ol></article><article class="model rendered"><p class="eyebrow">NIFT / RENDERED-SOURCE</p><h3>Nift <code>ai-sdk-agent</code><br>(rendered-source)</h3><p>Maintained HTML, metadata/navigation and coordinated reference projections. No routine Markdown/MDX content compiler.</p><ol><li>HTML + maintained projections</li><li>Bounded island SSR refresh</li><li>Nift composition + retained islands</li><li>Publication + search/runtime assets</li></ol></article></div><div class="note"><strong>Same accepted publication. Different maintenance contracts.</strong><p>These are complete orchestrated publication timings, not native Nift <code>&#64;markup</code> performance. The compatibility layer implements the pinned corpus’s required behavior, not a general Next.js replacement.</p></div>'''))
parts.append(section(2,'parity','Parity comes before the bars.','The migration acceptance target includes retrieval, interactive behavior and publication correctness.', '''<div class="proof-grid"><div><strong>1,674</strong><span>HTML routes</span></div><div><strong>1,386</strong><span>primary documents</span></div><div><strong>259</strong><span>recipe aliases</span></div><div><strong>29</strong><span>ancillary / home pages</span></div><div><strong>1,386</strong><span>Markdown endpoints</span></div><div><strong>506</strong><span>redirect patterns</span></div></div><div class="acceptance"><span class="eyebrow">FRESH-CLONE ACCEPTANCE</span><strong>3,219 files.<br>Every accepted byte.</strong><p>All publication/runtime files in each optimized migration match that project’s accepted fresh-clone output. This is not a claim that Next’s build-artifact inventory has the same file count.</p></div><div class="two"><article><h3>Content, retrieval and route lifecycle</h3><p>Nine v5/v6/v7 document/provider/cookbook families retain content, headings/anchors, metadata, version switching, local links and search. All Markdown endpoints match frozen bytes; seven discovery outputs, sitemap/robots and OG fixtures are separately checked.</p><p>Incremental publications equal forced recomputation. Add/rename/delete retire stale HTML and Markdown together. Missing or corrupt generated products recover correctly.</p></article><article><h3>72 browser states per migration</h3><p>Twelve representative docs/providers/cookbook/home paths, desktop/mobile and light/dark/system. System resolved light on this host. Optimization repeats 144 migration states against frozen upstream observations; the initial campaign covered 216 states across all three implementations.</p><p>Checks cover content, geometry, style, navigation, TOC, title and broken images. <strong>No universal pixel-identity claim:</strong> animation pixels and generated React IDs are outside equality.</p></article></div><p class="qualification">The link/CSS audit retains 21 inherited broken links and finds zero new failures. OG cards remain request-driven runtime output, using maintained fonts/background and metadata; normal builds do not generate a corpus of social cards.</p>'''))
parts.append(section(3,'islands','Static where possible.<br>React where useful.','Nift composition does not imply vanilla-only output. The migration retains the interactive parts rather than flattening them.', '''<div class="island-band"><span>OPAQUE STATIC CONTENT</span><b>+</b><span class="lit">INDEPENDENT REACT ISLANDS</span><b>→</b><span>HYDRATED PUBLICATION</span></div><div class="two"><article><h3>Real interaction stays</h3><p>Generation/loading demos, object generation, nested weather, prompts, media/playback, provider/model selection, recipes, tabs/copy, version switching, mobile navigation and search remain interactive.</p><p>React islands hydrate around opaque static HTML. The publication does not carry a Next application runtime. Simple content controls use lightweight browser code where appropriate.</p></article><article><h3>Build products have owners</h3><p>Actual esbuild dependency graphs govern independently cached client, SSR, shared chrome and runtime products. Unrelated content edits preserve island bundles; source/import/toolchain changes invalidate them.</p><p>983 mounts in 1,415 content/ancillary sources pass independent host-boundary checks. The content registry is still one eager entry across 16 island families: seven emitted outputs, 1,131,411 bytes. Shared chrome emits approximately 2,035,693 bytes.</p></article></div><p class="qualification">Emitted output bytes are not per-page download sizes; each family is not a separate bundle. Deterministic local AI/chat/feedback success/error fixtures verify UI and transport behavior, not live production AI, feedback or analytics. Registry splitting and dependency duplication remain future profiling targets.</p>'''))
bench=chart('Warm full publication','Complete production command · five serialized samples · median and range')
bench+='<div class="mode-charts">'+chart('Fresh application state','Generated application caches/products reset; maintained inputs, packages and OS caches remain.','fresh-application-state')+chart('Unchanged production command','Upstream still executes a production Next build. This is not a no-op or HMR test.','unchanged-cached')+'</div>'
bench+='<table class="measurements"><caption>Complete publication · median seconds, all five-run min–max ranges</caption><thead><tr><th scope="col">Workflow</th>'+''.join(f'<th scope="col">{x}</th>' for x in mode_labels)+'</tr></thead><tbody>'
for model,label in zip(models,labels):
 bench+=f'<tr><th scope="row">{label}</th>'
 for mode,ml in zip(modes,mode_labels):
  v=values(model,mode);bench+=f'<td data-label="{ml}"><strong>{med(v):.2f}s</strong><small>{min(v):.2f}–{max(v):.2f}s</small></td>'
 bench+='</tr>'
bench+='</tbody></table><div class="note"><strong>Production publication, not the Next editing loop.</strong><p>Upstream’s unchanged command still performs a production Next build. This is not a Next dev-server/HMR comparison. Fresh-state medians happen to be lower than warm-full medians here, with overlapping ranges; this does not establish a causal cold-state speed advantage.</p></div>'
parts.append(section(4,'benchmarks','Measure the whole publication.','Preparation, framework work, Nift composition, references, search and runtime/asset publication remain inside each workflow’s command.',bench))
t='<table class="measurements changed"><caption>Controlled input cases · one production-publication observation per workflow/case, not five-sample medians</caption><thead><tr><th scope="col">Changed input</th>'+''.join(f'<th scope="col">{x}</th>' for x in labels)+'</tr></thead><tbody>'
change_labels=['1 document body','10 document bodies','100 document bodies','Metadata update / remove','Shared layout','Navigation order','Historical version','Provider / reference','Redirect','Island source','Route add','Route rename','Route delete']
for row,title,target in zip(u,change_labels,expected_changes):
 case=row['case'];hr=next(x for x in h if x['case']==case);ar=next(x for x in (c if case in co else a) if x['case']==co.get(case,case));v=[row['elapsed_s'],hr['incremental_s'],ar['incremental_s']];assert tuple(round(x,2) for x in v)==target
 t+=f'<tr><th scope="row">{title}</th>'+''.join(f'<td data-label="{esc(l)}"><strong>{x:.2f}s</strong></td>' for l,x in zip(['Upstream','Nift authored','Nift rendered'],v))+'</tr>'
t+='</tbody></table>'
parts.append(section(5,'iteration','Make the changed-input costs visible.','These are complete production publications after controlled edits. Editing and coordination labor are outside elapsed build time.', '''<div class="iteration-head"><div><span>ONE BODY / NIFT AUTHORED</span><strong>13.19<small>s</small></strong></div><div><span>ONE BODY / NIFT RENDERED</span><strong>7.83<small>s</small></strong></div><p>One/ten-page edits in the scoped rendered pipeline compose one/ten HTML files. Search, metadata scans and shared publication still impose fixed costs.</p></div><p class="qualification"><strong>Every Nift incremental output equals forced recomputation.</strong> Upstream rows are full production rebuilds, not Next HMR/dev-server timings. These numbers do not measure which development server offers the better live editing experience.</p>'''+t+'''<p class="qualification">Rendered-source body edits coordinate HTML, search metadata, Markdown downloads and LLM references. Metadata also coordinates navigation/sitemap; historical/provider rows use the complete coordinated cases, not faster HTML-only probes. Each upstream case uses an isolated pinned warm application state; rename/delete start with the prior fixture already published. Historical v5 mutates a local cached source fixture, not acquisition of a new release. Maintained inputs are restored.</p>'''))
parts.append(section(6,'profiling','The first faithful build was not the finish.','Parity first → profile → remove redundant work → revalidate → benchmark.', '''<div class="profile-history"><article><p class="eyebrow">INITIAL / SINGLE DIAGNOSTICS</p><h3>140.712s <span>authored</span><br>91.409s <span>rendered</span></h3><p>Faithful, but expensive. Authored MDX compatibility/SSR took 89.101s; Markdown downloads 24.902s. Whole-DOM rendered island refresh took 62.036s.</p></article><article><p class="eyebrow">OPTIMIZED / SINGLE DIAGNOSTICS</p><h3>53.642s <span>authored</span><br>25.673s <span>rendered</span></h3><p>Bounded workers and retained reuse; lexical island host spans and batched SSR. These diagnostic runs are not the final five-sample production medians of 83.16s and 37.96s.</p></article></div><div class="two"><article><h3>Reuse the work that is actually shared</h3><p>Four bounded workers reuse content-addressed compiled bodies: 201 compilations are reused within 1,386 documents. Metadata, compiler/body and renderer keys are distinct. Version-menu props retain only relevant ancestors/fallback; 5,022 mapping checks match the complete original resolver.</p><p>Search is version-scoped, Markdown projections source-scoped and discovery depends on actual projection bytes. Generated products validate input graphs and output hashes.</p></article><article><h3>Keep the rejected experiment</h3><p>Retaining every unique Shiki HAST/compiled file made things worse: MDX rose to 108.15s and maximum individual process/phase RSS to about 2.49 GiB. That broad cache was rejected.</p><p>The accepted design keeps reused bodies only until their last use, with a bounded repeated-input Shiki cache. Rendered island refresh replaces only host interiors rather than reparsing whole documents.</p></article></div><p class="qualification">Single diagnostic observations and final campaign medians are different evidence classes. They are not interchangeable optimization percentages. The report and raw history retain both, including failed/interrupted benchmark preparation with no accepted samples.</p>'''))
phase_expected={'MDX compatibility and server rendering':44.17,'Markdown projection conversion':10.95,'shared page UI preparation':12.41,'search indexing':6.32,'Nift composition':3.17}
def phase(model,name,mode='warm-full'):
 return med([next(p['elapsed_s'] for p in x['phases'] if p.get('name',p.get('stage'))==name) for x in pick(model,mode)])
for name,e in phase_expected.items():assert round(phase('ai-sdk',name),2)==e
comp='<div class="costs">'+''.join(f'<div><strong>{phase("ai-sdk",name):.2f}s</strong><span>{esc(name)}</span></div>' for name in phase_expected)+'</div>'
comp+='''<p>The authored pipeline derives more representations: MDX/SSR, Markdown downloads, reference projections, search, navigation, shared UI and publication. The rendered pipeline maintains closer-to-final HTML and references, while still doing island refresh, shared UI, search and publication.</p><p><strong>The composition phase includes preparation and the Nift CLI.</strong> Bare Nift is only one part of the complete pipeline; these are not native Markdown-renderer timings.</p>'''
for model,label in zip(models,labels):
 names=[p.get('name',p.get('stage')) for p in pick(model,'warm-full')[0]['phases']]
 comp+=f'<details><summary>{label} · all sequential component medians</summary><table class="measurements"><caption>Seconds · five-sample phase medians; their medians need not sum to the complete-pipeline median</caption><thead><tr><th scope="col">Phase</th>'+''.join(f'<th scope="col">{x}</th>' for x in mode_labels)+'</tr></thead><tbody>'
 for name in names:comp+=f'<tr><th scope="row">{esc(name)}</th>'+''.join(f'<td data-label="{ml}">{phase(model,name,mode):.3f}s</td>' for mode,ml in zip(modes,mode_labels))+'</tr>'
 comp+='</tbody></table></details>'
comp+='''<p class="qualification">Upstream’s Fumadocs CLI generates source/index modules; actual MDX compilation and highlighting also run inside Next’s production-build stage. Shiki nests inside transforms; concurrent worker task sums can exceed wall time. Do not add nested or concurrent counters to sequential elapsed phases. The initial uninstrumented I/O counter of zero is not evidence of zero filesystem work.</p>'''
parts.append(section(7,'components','Authored source earns its extra work.','The five warm-full authored component medians explain the source-model difference more precisely than “Markdown is slower.”',comp))
mem=chart('Warm-full individual process / phase RSS','GNU maximum RSS · maximum measured individual process/phase · five-sample medians','warm-full','maximum_process_phase_rss_kib',1024,30000,'MiB')
mem+='''<div class="note"><strong>Individual RSS is not the worker pool’s total footprint.</strong><p>A supplemental nominal 50 ms sampler sums live descendant RSS, with scan overhead. Shared pages may be counted more than once; short peaks may be missed. This is approximate and not exact aggregate resident memory or an OS peak.</p></div>'''
mem+='<table class="memory"><caption>Warm-full medians · separate memory scopes · five runs</caption><thead><tr><th scope="col">Workflow</th><th scope="col">Individual process/phase</th><th scope="col">Sampled descendant RSS sum</th></tr></thead><tbody>'
for model,label in zip(models,labels):
 mem+=f'<tr><th scope="row">{label}</th>'
 for key,div,scope in [('maximum_process_phase_rss_kib',1024,'Individual'),('sampled_peak_sum_rss_bytes',1024**2,'Sampled tree')]:
  v=values(model,'warm-full',key,div);mem+=f'<td data-label="{scope}"><strong>{med(v):,.1f} MiB</strong><small>{min(v):,.1f}–{max(v):,.1f}</small></td>'
 mem+='</tr>'
mem+='</tbody></table><p class="qualification">For the authored worker pool, the sampled warm median is 4,380.7 MiB, despite a 901.8 MiB maximum individual-process median. Both scopes matter. The A10 reports retain all fresh/unchanged memory distributions as well.</p>'
parts.append(section(8,'memory','Name the memory scope.','The gap is substantial. The measurement definitions stay attached to it.',mem))
parts.append(section(9,'maintenance','Faster is not automatically preferable.','Choose the maintained source contract, then judge its publication pipeline.', '''<div class="two"><article class="contract authored"><p class="eyebrow">NIFT ai-sdk (AUTHORED-SOURCE)</p><h3>One authority. Derived projections.</h3><p>Markdown/MDX/frontmatter and structured versions remain authoritative, readable and easier to review. Downloads, search and LLM references derive from source; retained islands have independent ownership.</p><p><strong>Cost:</strong> transformation work, a bounded compatibility layer and internal Geistdocs/Fumadocs coupling. Four pinned internal Geistdocs UI modules and one private Fumadocs search reader are explicit maintenance liabilities.</p></article><article class="contract rendered"><p class="eyebrow">NIFT ai-sdk-agent (RENDERED-SOURCE)</p><h3>Less transformation. More coordination.</h3><p>Faster publication and no routine MDX compiler. Agents can maintain HTML directly.</p><p><strong>Cost:</strong> edits must coordinate HTML, search data, Markdown downloads, LLM references and metadata/navigation. The benchmark excludes the effort of making those changes consistent.</p></article></div><div class="note"><strong>Upstream remains a credible third option.</strong><p>Next.js/Geistdocs also has authoritative source and stronger native framework, development and deployment integration. The production build measurements do not measure every advantage of that ecosystem.</p></div><p>Fonts and compiled stylesheets are maintained publication assets with explicit update workflows. Homepage statistics and model catalogs are pinned maintained snapshots, while upstream retains public npm/GitHub requests and timeout fallbacks. These architectural differences remain part of the comparison.</p><h3>Remaining costs are future profiling targets</h3><p>MDX/highlighting, derived reference work, shared shell SSR, corpus metadata/hash scans, per-version search export and publication copying remain real costs. Navigation legitimately fans out over its tree. Registry splitting, dependency duplication, startup/scan overhead, search granularity and concurrent-memory reductions deserve later investigation. They do not reopen this accepted experiment.</p>'''))
parts.append(section(10,'opinion','An explicit three-way judgement.','Codex assessed Upstream Next.js/Geistdocs, Nift authored-source and Nift rendered-source—not the repo name in isolation.', '''<div class="two"><article class="verdict"><p class="eyebrow">AGENTS IMPLEMENT / HUMANS DIRECT</p><h3>Preferred: Nift <code>ai-sdk</code><br>(authored-source)</h3><p>One authoritative source, lower coordination burden, independently retained islands and much lower measured publication time/memory than upstream. The additional transformation cost is acceptable for consistency.</p></article><article class="verdict"><p class="eyebrow">HUMANS + AGENTS BOTH EDIT</p><h3>Preferred: Nift <code>ai-sdk</code><br>(authored-source)</h3><p>Markdown/MDX/frontmatter and structured sources are easier to edit and review. The rendered-source speed does not outweigh the stronger source-of-truth model.</p></article></div><div class="counterfactual"><span class="eyebrow">REMOVE MIGRATION EFFORT + INCUMBENCY</span><p>Codex still prefers <strong>Nift <code>ai-sdk</code> (authored-source)</strong> in both maintenance scenarios.</p></div><p class="qualification">This accepts the bounded adapter burden for the demonstrated publication architecture. Upstream is credible when native development/deployment integration takes priority; the experiment does not fully measure that tradeoff. Official adoption still requires a deployment/backend pilot.</p>'''))
parts.append(section(11,'official','Worth evaluating. Not a migration decree.','The evidence justifies Vercel evaluating a migration from the current Next.js/Geistdocs AI SDK docs application to Nift composition with retained React islands.', '''<div class="two"><article><h3>Why investigate seriously</h3><p>Complete production publication is materially faster with lower measured memory, while maintaining authored content and real interactive islands. Controlled production edits, complete output coverage and fresh-clone reproduction make this an engineering result worth testing in a real deployment.</p></article><article><h3>What a production pilot must resolve</h3><p>Host/runtime deployment, process rollover, private API credentials, AI/chat/feedback/search integration and analytics. Local fixtures do not certify those services. Internal module coupling, maintained asset/snapshot updates and native Next tooling must enter the decision.</p></article></div><p class="qualification"><strong>A serious deployment/backend evaluation, not an unconditional recommendation.</strong> Build performance alone does not establish that Vercel should migrate the official site. The external playground remains separately hosted.</p>'''))
parts.append(section(12,'guidance','The islands lesson is discoverability.','Dogfooding nift init --migration did not reveal a framework prohibition.',f'''<p>Generated guidance already permits React, Vue, Svelte and other tools. What needed stronger visibility was island composition and explicit ownership of client/SSR products, dependencies, emitted bytes and invalidation.</p><p>Future guidance should make “the lightest faithful solution” concrete: Nift composes the publication; neighboring tooling owns useful interactive islands. It should distinguish maintained assets from derived products, authoritative versus coordinated source models, remote-service evidence, pinned versions and full/cached/fresh build scope.</p><p>{link(H+'/investigation/MIGRATION-INIT-REVIEW.md','Dedicated review and exact wording/scaffolding proposals')}</p><p class="qualification">These are proposals for later guidance work. No Nift core or generated migration-template source was changed during this experiment.</p>'''))
parts.append(section(13,'methodology','Keep the boundaries in view.','A production benchmark is useful when readers can see exactly what it includes and excludes.', '''<div class="method-grid"><article><h3>Commands + pinned inputs</h3><p>Upstream: <code>pnpm --dir apps/docs build:site</code>, including sync, Fumadocs and Next production build. Migrations: <code>python3 scripts/build-content.py</code> (forced for full modes), including preparation, bundling, Nift, reference outputs, search and asset/runtime publication.</p><p>Node 24.21.0, pnpm 11.23.0, Nift 4.8.0. Upstream keeps its pinned eight-CPU Next setting; authored MDX uses four bounded workers. Six public external image responses are frozen. No private credentials or real backend submissions.</p></article><article><h3>Sampling + state</h3><p>Five serialized samples for each of three modes and workflows, rotating project order: 45 accepted publications. Active host; OS cache state uncontrolled. Fresh application state clears generated application caches/products, keeps maintained assets and installed packages, and is not machine cold.</p><p>Dependency installation, state-reset/archive preparation, input mutation and verification are excluded. Input-case observations are single runs, not distributions.</p></article><article><h3>What is not measured</h3><p>Next dev-server/HMR, source-editing/review labor, deployment transfer, host/process startup, production backend latency or private AI/feedback/analytics integration. Local deterministic fixtures establish a narrower UI/transport contract.</p><p>Preview robots keep <code>Disallow: /</code>; production indexing policy needs deployment configuration. Runtime changes require the deployment runtime to roll over.</p></article><article><h3>Accounting + limitations</h3><p>Individual process/phase RSS and approximate sampled descendant RSS sums differ. Nested Shiki/task counters are not additive. Phase medians need not sum to pipeline medians.</p><p>Next’s build/runtime artifacts and standalone public/runtime files have different transport inventories; raw file-count equality is not claimed. Coverage and output hashes are established by separate parity gates.</p></article></div>'''))
evidence=[('https://github.com/nift-experiments/ai-sdk','Authored-source repository'),('https://github.com/nift-experiments/ai-sdk-agent','Rendered-source repository'),(UP,'Exact upstream source pin'),(H+'/investigation/A10-REPORT.md','Authored A10 report'),(A+'/investigation/A10-REPORT.md','Rendered A10 report'),(H+'/investigation/A8-INITIAL-PROFILING.md','Initial and rejected profiling'),(H+'/investigation/A9-PROFILING.md','Optimization and counter scopes'),(H+'/investigation/A9-BROWSER-MATRIX.json','Authored optimized browser matrix'),(A+'/investigation/A9-BROWSER-MATRIX.json','Rendered optimized browser matrix'),(H+'/investigation/A9-INTERACTIONS.json','Retained interaction checks'),(H+'/investigation/A9-FRESH-CLONE-PROOF.json','Authored fresh-clone proof'),(A+'/investigation/A9-FRESH-CLONE-PROOF.json','Rendered fresh-clone proof'),(H+'/investigation/MIGRATION-INIT-REVIEW.md','Migration-init review'),(H+'/investigation/benchmark-evidence/final-benchmark/samples.json','All 45 raw publication samples'),(H+'/investigation/benchmark-evidence/changed-input-upstream/samples.json','13 upstream changed-input cases'),(H+'/investigation/benchmark-evidence/SHA256SUMS.json','555 retained evidence hashes'),(H+'/investigation/benchmark-tools/README.md','Benchmark reproduction'),(H+'/scripts/verify-lifecycle-body.py','Authored incremental/forced lifecycle harness'),(A+'/scripts/verify-lifecycle-coordinated.py','Rendered coordinated maintenance harness')]
# Repository harness names must be verified before the generated link is accepted.
parts.append(section(14,'evidence','A report you can trace back.','Both completed migration repositories remain untouched by this Labs publication. Evidence links pin the accepted report commits.', '<div class="evidence-grid">'+''.join(link(url,text) for url,text in evidence)+'</div><p class="small">Upstream pin <code>3ebefff610f96892c50be48cf1838c453e2349f7</code>. Report pins: authored <code>6d07d2f06a96d33deac0384514574d069cce98b7</code>; rendered <code>524b1840a0a36d0dafdfbc368f52fb526951bad8</code>. Measured implementation heads are retained in the raw sample records; these later commits add final reporting evidence.</p>'))
parts.append('''</main><footer class="wrap footer"><a class="brand" href="@path('/')">NIFT <span>LABS</span></a><p>Independent experiments. Preserved evidence. Useful tradeoffs.</p><a href="@path('sites/')">Explore the notebook ↗</a></footer>''')
(R/'content/sites/ai-sdk/index.html').write_text(__import__('iteration_memory').inject('\n'.join(parts)+'\n', 'ai-sdk'))
print('PASS: 45 samples, 9 headline medians, 13 coordinated input rows, memory/component headlines, 144 browser states and both fresh clones; article rendered.')
