"""Reproduce the Temporal Labs report from SHA-verified accepted T9 evidence."""
from pathlib import Path
import json,hashlib,html
R=Path(__file__).resolve().parents[1];D=R/'content/sites/temporal/data'
for n,h in json.loads((D/'provenance.json').read_text()).items():assert hashlib.sha256((D/n).read_bytes()).hexdigest()==h
v=json.loads((D/'visual.json').read_text());assert len(v)==32 and sum(x['pixelIdentical'] for x in v)==21 and all(x['geometryIdentical'] and (x['pixelIdentical'] or (x['changedPixels']==21 and x['maxChannelDifference']==1)) for x in v)
s=json.loads((D/'summary.json').read_text());models=['upstream','temporal','temporal-agent'];labels=['Upstream Temporal Docusaurus','Nift temporal (authored-source)','Nift temporal-agent (rendered-source)']
for mode,expected in [('warm-full',[34.16,26.05,10.35]),('fresh-app',[289.64,26.44,10.61]),('unchanged',[44.64,1.77,1.32])]:
 for m,v in zip(models,expected):assert s['scenarios'][mode][m]['samples']==5 and round(s['scenarios'][mode][m]['wall_seconds']['median'],2)==v
changes=s['changes']+s['lifecycle'];assert len(changes)==26 and all(x['independent_clean_forced_equal'] and not x['differences'] for x in changes)
assert all(x['byte_manifest_equals_working_publication'] and x['source_clean'] for x in s['fresh_clones'])
def sec(n,id,title,body):return f'<section class="chapter" id="{id}"><p class="eyebrow">Event {n:02} / {id}</p><h2>{title}</h2>{body}</section>'
def table(headers,rows):return '<div class="tablewrap"><table><thead><tr>'+''.join('<th scope="col">'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def stat(mode,m,key='wall_seconds',digits=2):
 d=s['scenarios'][mode][m][key];return f"<strong>{d['median']:,.{digits}f}</strong><small>{d['range'][0]:,.{digits}f}–{d['range'][1]:,.{digits}f}</small>"
def chart(title,mode,key,axis,unit):
 out=f'<figure class="chart"><h3>{title}</h3><div class="axis"><span>0</span><span>{axis/2:g}</span><span>{axis:g} {unit}</span></div>'
 for m,l,c in zip(models,labels,['upstream','authored','rendered']):
  d=s['scenarios'][mode][m][key];v=d['median'];out+=f'<div class="signal {c}"><div class="label"><span>{l}</span><strong>{v:,.2f} {unit}</strong></div><div class="rail" aria-hidden="true"><i style="width:{100*v/axis:.4f}%"></i></div><p class="range">{d["range"][0]:,.2f}–{d["range"][1]:,.2f} {unit} · five samples</p></div>'
 return out+'</figure>'
p=['''<header class="mast"><a class="brand" href="@path('/')">NIFT LABS</a><nav aria-label="Report navigation"><a href="#parity">Parity</a> · <a href="#publication">Publication</a> · <a href="#iteration">Iteration</a> · <a href="#opinion">Judgement</a></nav><a href="@path('sites/')">All experiments ↗</a></header><main id="main"><section class="hero"><div><p class="eyebrow">Experiment 07 / Temporal Docs / October 2026</p><h1>Replay the work.<br><em>Change the<br>pipeline.</em></h1><p class="lead">962 routes. Retained React islands. Two maintained source models.</p><p>A production-scale Temporal documentation migration from Docusaurus to Nift composition. Preserve the publication, test the dependency boundaries, then measure the complete workflow.</p><p class="qualification">Independent Nift Labs research. No Temporal endorsement. No Nift core or migration-template changes.</p></div><aside class="history" aria-label="Experiment event history"><p class="eyebrow">Accepted history / T0–T9</p><div class="event"><small>01 / CAPTURE</small><strong>962 routes</strong></div><div class="event"><small>02 / PRESERVE</small>Content + React behavior</div><div class="event"><small>03 / REPLAY</small>Independent forced recomputation</div><div class="event"><small>04 / MEASURE</small>Complete production publication</div><div class="event"><small>05 / DECIDE</small>Authored source wins the maintenance tradeoff</div></aside></section><nav class="reading" aria-label="Reading order"><a href="#architectures">Source models</a><a href="#parity">Prove parity</a><a href="#iteration">Everyday feedback</a><a href="#evidence">Inspect evidence</a></nav>''']
p.append(sec(1,'architectures','Three implementations. Two Nift source models.','''<p><strong>Upstream Temporal Docusaurus</strong> is the original implementation. <strong>Nift <code>temporal</code> (authored-source)</strong> and <strong>Nift <code>temporal-agent</code> (rendered-source)</strong> are independent migrations with different maintained inputs.</p><div class="two"><article><h3>Nift <code>temporal</code> (authored-source)</h3><pre>Maintained Markdown/MDX/frontmatter
+ structured references
→ pinned corpus compiler / retained component renderer
→ transient HTML + derived navigation/downloads/LLM products
→ Nift composition
→ publication + retained React islands</pre></article><article><h3>Nift <code>temporal-agent</code> (rendered-source)</h3><pre>Maintained HTML + explicit metadata/navigation
+ pre-derived downloads/LLM views
→ retained shell/island composition
→ Nift composition
→ publication + retained React islands</pre></article></div><p>React remains where appropriate. The authored path uses the pinned MDX compiler and retained components; the rendered path maintains finished HTML and initial island markup. This is a corpus-bounded migration, not a general Docusaurus replacement.</p>'''))
p.append(sec(2,'parity','First, preserve the site.','''<div class="metrics"><div><strong>962</strong>HTML routes</div><div><strong>793</strong>primary documentation pages</div><div><strong>832</strong>ancillary Markdown/text/sitemap products</div><div><strong>1,130</strong>retained non-framework assets</div><div><strong>792</strong>maintained unique OG cards</div><div><strong>567</strong>redirect rules</div></div><p>All 962 route semantic projections pass. All 4,544 highlighted code blocks match. Ancillary products and retained assets preserve accepted bytes, with no new missing local targets.</p><p>Each migration passed 132 browser states and 49 interaction observations, then reproduced from fresh public clones. Across 32 screenshot comparisons, 21 are pixel-identical; the other 11 each differ in only 21 pixels, with maximum channel delta 1: tiny rasterization noise, not universal pixel identity.</p><p class="qualification">Framework artifacts differ intentionally: the upstream publication has 3,984 files; each Nift publication has 2,996. The contract covers publication semantics, retained products/assets and behavior rather than identical framework bundle sets. Search UI uses local transport fixtures; live Algolia/backend services were not exercised. Mermaid behavior is retained in the browser.</p>'''))
p.append(sec(3,'publication','Measure the whole publication.', '<p class="lead">Docusaurus puts up a respectable warm-full fight. Fresh state and unchanged publication tell a different story.</p>'+table(['Scenario / seconds']+labels,[[title]+[stat(mode,m) for m in models] for mode,title in [('warm-full','Warm full'),('fresh-app','Fresh application state'),('unchanged','Unchanged normal command')]])+'''<p class="qualification">Five serialized samples per cell; median above observed min–max range. Active shared host; OS caches uncontrolled. Installed dependencies retained and acquisition excluded.</p><div class="charts">'''+chart('Warm full publication','warm-full','wall_seconds',40,'s')+chart('Fresh application state','fresh-app','wall_seconds',320,'s')+'''</div><details><summary>Scenario definitions and cohort boundaries</summary><ul><li>Warm full: complete upstream <code>yarn build</code>; Nift force recomputation of conversion, bundles, projections and composition.</li><li>Fresh application state: generated application caches/output cleared; dependencies retained. Nift maintained OG source assets remain. This is not machine-cold.</li><li>Unchanged: complete normal production command with unchanged maintained inputs.</li></ul><p>Upstream warm-full and unchanged use the same command, in separate chronological cohorts. Their differing medians reflect observed cohort variation, not different build algorithms. Docusaurus development server/HMR is not measured.</p></details>'''))
og=s['scenarios']['fresh-app']['upstream']['og_stats'];import statistics
ogmed=statistics.median(x['renderMs']/1000 for x in og)
p.append(sec(4,'ownership','Fresh state exposes asset ownership.',f'''<div class="callout"><p class="eyebrow">OG cache / explicit maintenance</p><h3>{ogmed:.1f}s median upstream OG render duration</h3><p>Clearing upstream application state also clears the OG cache. Its plugin regenerates the cards. Both Nift projects maintain the 792 unique accepted cards as static assets: normal publication copies them, and intentional metadata/title changes use an explicit selective refresh workflow.</p><p><strong>Nift did not generate 792 cards in 26 seconds.</strong> The fresh-state result includes an intentional change in asset ownership.</p></div><p>Upstream also reclones the public cookbook during every prebuild. Authored Nift keeps a pinned maintained local snapshot; updating it is explicit maintenance. Upstream network acquisition remains visible in its complete command.</p>'''))
rows=[]
for case in dict.fromkeys(x['case'] for x in changes):
 vals=[next(x for x in changes if x['project']==m and x['case']==case) for m in models[1:]];rows.append([case]+[f"{x['incremental_seconds']:.3f}s" for x in vals])
p.append(sec(5,'iteration','The feedback loop is the daily workload.','''<p class="lead">Developers and agents usually change a few pages, metadata fields, diagrams, navigation entries or components. Iteration matters as much as full publication.</p>'''+table(['Change','Nift authored-source','Nift rendered-source'],rows)+'''<p><strong>All 26 changed-input/lifecycle publications matched independent forced recomputation.</strong> These are single observations per case, not five-sample medians.</p><p>Representative upstream production rebuild observations: body edit <strong>40.249s</strong>; navigation <strong>37.885s</strong>. They do not measure Docusaurus HMR.</p><details><summary>Publication versus maintenance-inclusive operations</summary><p>Metadata publication excludes explicit OG refresh: whole operations were 4.936s authored and 2.144s rendered. Rendered island-source work includes explicit initial-markup maintenance; whole operation 12.229s versus 10.956s publication. Authored island-source 17.215s already includes its derived work.</p><p>Route-add OG setup occurred outside publication timing; no whole-operation duration is claimed. Rendered fixtures coordinate HTML, downloads and LLM views rather than deriving those views automatically. Explicit maintenance memory is outside publication RSS.</p></details><p>Shared layout and navigation still fan out. Rendered source is not uniformly faster: shared layout costs 9.941s versus authored 8.877s. Route lifecycle work remains substantial, and these are future profiling targets.</p>'''))
p.append(sec(6,'profiling','Keep the first implementation in the history.','''<p>Initial five-sample warm-full medians were 37.867s upstream (35.153–40.636), 27.366s authored (26.259–30.420), and 11.434s rendered (9.905–13.016).</p><div class="history"><p>Faithful implementation → profile → tighten dependencies/caches → inject corruptions and test repair → revalidate parity → final benchmark</p></div><p>T8 fixed a real stale transitive imported-MDX TOC case affecting two pages. Eleven corruption-repair cases tested retained caches and products. Initial and rejected evidence remain available: optimization only counts after replaying the correctness gates.</p><p>Shared shell work, route/catalog invalidation, projection generation and component bundling remain costs. Some final rendered shared-change observations are slower than their initial probes; the result is evidence for future tooling work, not a promise that every row improves.</p>'''))
p.append(sec(7,'memory','Less measured memory, with the scopes attached.','<div class="charts">'+chart('Maximum individual process/phase RSS','warm-full','maximum_individual_descendant_rss_mib',7500,'MiB')+chart('Sampled descendant resident-page sum peak','warm-full','sampled_descendant_rss_sum_peak_mib',7500,'MiB')+'</div><p class="qualification">Warm-full five-sample medians and observed ranges. Maximum individual process/phase RSS is not aggregate memory. The sampled descendant sum polls about every 50ms, can double-count shared pages, can miss short peaks, and is not PSS. Explicit maintenance operations are outside these publication measurements.</p>'))
comp=[]
for m in models[1:]:
 c=s['components']['warm-full-'+m];comp.append('<article><h3>'+labels[models.index(m)]+'</h3>'+table(['Component','Median seconds'],[[k.replace('_',' '),f"{v['median']:.3f}"] for k,v in c.items() if k!='complete'])+'</article>')
p.append(sec(8,'components','Composition is a small part of the pipeline.','<div class="two">'+''.join(comp)+'</div><p>The authored path spends about 10.12s in Markdown/MDX, 6.15s in shell/dependencies, 2.30s in the component server bundle, 2.62s in React SSR and 1.67s deriving Markdown downloads. Rendered source avoids routine Markdown conversion but retains shared shell and browser-bundle work.</p><p><strong>These are complete publication workflows, not bare Nift composition or native markup-renderer timings.</strong> Nift composition is about 0.33s authored and 0.32s rendered. Phase medians do not add exactly to command medians; startup/preparation and unattributed work remain.</p>'))
p.append(sec(9,'maintenance','Three codebases, three ownership tradeoffs.','''<div class="three"><article><h3>Upstream Temporal Docusaurus</h3><p>Established ecosystem, conventional Docusaurus/React tools, native component workflow and familiar contributor model.</p><p>Higher measured publication time and memory, expensive fresh-state work and broader production rebuilds.</p></article><article><h3>Nift <code>temporal</code> (authored-source)</h3><p>Markdown/MDX/frontmatter and structured references stay authoritative. Companion products derive automatically; explicit dependencies and retained React islands support faster production iteration.</p><p>Owns a bounded project compiler/cache/island adapter layer. Shared runtime and navigation changes still fan out.</p></article><article><h3>Nift <code>temporal-agent</code> (rendered-source)</h3><p>Fastest publication and very cheap body iteration; fewer routine transformations.</p><p>Maintainers coordinate HTML, initial island markup, downloads, LLM projections, metadata and navigation. Those representations can drift without explicit validation.</p></article></div>'''))
p.append(sec(10,'opinion','Prefer authoritative source for maintenance.','''<div class="two"><article><p class="eyebrow">Agents implement, humans direct</p><h3>Preferred: Nift <code>temporal</code> (authored-source)</h3><p>One authoritative Markdown/MDX/frontmatter source derives companion products. Rendered-source speed does not outweigh the coordination burden. Publication time and measured memory improve over upstream, while retained React islands preserve practical interaction.</p></article><article><p class="eyebrow">Humans and agents both edit</p><h3>Preferred: Nift <code>temporal</code> (authored-source)</h3><p>Human-readable source, reviewable diffs and familiar content organization. The iteration loop is fast enough, and fewer synchronized representations make maintenance easier.</p></article></div><p><strong>Even if migration effort and incumbency were removed, Codex still prefers Nift <code>temporal</code> (authored-source) for both scenarios.</strong> This is an engineering judgement among all three implementations, not a benchmark-derived universal rule.</p>'''))
p.append(sec(11,'evaluation','A serious evaluation from Docusaurus to Nift.','''<p class="lead">The evidence supports Temporal seriously evaluating a migration from Docusaurus to Nift with retained React islands.</p><p>It does not establish an unconditional migration recommendation. Live search/backend/deployment integration, editor and component workflows, adapter/library upgrades and long-term compatibility ownership need evaluation. Docusaurus ecosystem benefits remain real.</p>'''))
p.append(sec(12,'guidance','Dogfood the migration guidance.','''<p><code>nift init --migration</code> was used as intended; an older manual playbook did not replace it. No Nift core or migration-template changes were made.</p><p>Future guidance candidates: explicit transitive dependency inventories, route/catalog invalidation, shared-shell fan-out, projection ownership, island/OG maintenance and adapter review. Keep those proposals separate from this accepted migration.</p>'''))
p.append(sec(13,'methodology','Keep the measurement boundaries visible.','''<ul><li>Five serialized samples for full/fresh/unchanged scenarios, rotating implementations on an active shared host. OS caches uncontrolled; fresh application state is not machine-cold.</li><li>Pinned sources, installed dependencies outside timing. Upstream cookbook network fetch remains inside its prebuild. Nift uses maintained OG assets and a pinned cookbook snapshot.</li><li>Changed-input cases are single observations, validated against independently forced output. Production publication is separate from unmeasured development/HMR.</li><li>Search UI parity uses fixtures; no live Algolia crawl/upload/backend claim. Deployment services were not benchmarked.</li><li>One upstream attempt returned success after a public GitHub HTTP/2 fetch failure produced an offline cookbook placeholder. Its wrong-corpus result was rejected; the unchanged exact command succeeded on retry without source changes. Raw log retained.</li><li>Complete Nift pipelines include project-side compilation, retained React, projections and publication. RSS scopes and excluded maintenance costs stay separate.</li></ul>'''))
H='https://github.com/nift-experiments/temporal/blob/8d82e1a1f746a8c690abb700fb493855ae822bcc';A='https://github.com/nift-experiments/temporal-agent/blob/bdc0c2637636822466f4e033c14acbfbf1f2e0a0'
links=[('Authored-source repository','https://github.com/nift-experiments/temporal'),('Rendered-source repository','https://github.com/nift-experiments/temporal-agent'),('Final report',H+'/investigation/FINAL-REPORT.md'),('Rendered-source final report',A+'/investigation/FINAL-REPORT.md'),('T7 initial profiling',H+'/investigation/T7-INITIAL-PROFILING.md'),('T8 optimization and parity',H+'/investigation/T8-OPTIMIZATION.md'),('Final raw summary',H+'/investigation/t9/t9-final-summary.json'),('Campaign index',H+'/investigation/t9/t9-campaign-index.json'),('Public-clone proof',H+'/investigation/t9/t9-clean-clones/result.json'),('Migration-init review',H+'/investigation/MIGRATION-INIT-REVIEW.md'),('Screenshot comparison',H+'/investigation/t8/t8-visual-comparison.json'),('Rejected wrong-corpus attempt',H+'/investigation/t9/t9-upstream-unchanged-4/production.log'),('Pinned upstream Temporal','https://github.com/temporalio/documentation/tree/5d9703a237a9efc9a7da48ac09f79526823b8182')]
p.append(sec(14,'evidence','Inspect, clone, reproduce.','<ul>'+''.join(f'<li><a href="{u}">{html.escape(l)} ↗</a></li>' for l,u in links)+'</ul><p>Use each migration README for pinned Node/Yarn/Nift prerequisites, dependency installation, normal/forced publication, explicit OG refresh and island-maintenance workflows. The final report records measured revisions, commands, source scope and acceptance gates.</p><pre>yarn install --frozen-lockfile --ignore-scripts --non-interactive\nyarn build\nyarn build:force</pre>'))
p.append('<footer>Accepted T0–T9 experiment · Independent Nift Labs · <a href="@path(\'sites/\')">More website experiments</a></footer></main>')
(R/'content/sites/temporal/index.html').write_text('\n'.join(p)+'\n')
print('PASS: frozen hashes, nine five-sample medians, 26 forced comparisons and public clones; report rendered.')
