#!/usr/bin/env python3
"""Explicit publication from externally validated, immutable official evidence."""
import argparse,hashlib,html,json,statistics,subprocess,sys,shlex
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SYSTEMS=['make','ninja','nift'];COLORS={'make':'#eabb63','ninja':'#e69586','nift':'#a3fb68'}
NAMES={'make':'GNU Make','ninja':'Ninja','nift':'Nift'}
SCENARIOS={'full':'Clean full','noop':'Warm no-op','leaf':'Leaf source','private':'Private header','medium':'Module header','global':'Global header','generated':'Generated input','batch10':'10 sources','batch10pct':'10% sources','target':'Targeted module','relink':'Relink only','clean-rebuild':'Clean + rebuild'}
def esc(s):return html.escape(str(s))
def fmt(x):return f'{x:,.3f}'
def table(caption,headers,rows):
 return '<div class="table-scroll" tabindex="0" role="region" aria-label="'+esc(caption)+'"><table><caption>'+esc(caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+esc(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">' if i==0 else '<td>')+esc(c)+('</th>' if i==0 else '</td>') for i,c in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'
def section(anchor,number,title,body):return f'<section class="report" id="{anchor}"><div class="block-title"><p class="eyebrow">{number} / {anchor}</p><h2>{title}</h2></div>{body}</section>'
def render(evidence,commit,series):
 assert len(commit)==40 and all(c in '0123456789abcdef' for c in commit)
 summary=json.loads((evidence/'summary.json').read_text());identity=summary['identity'];validation=json.loads((evidence/'validation.json').read_text());assert validation['all_passed'] and not identity['suite_dirty'];assert identity['plan']['kind']=='official-same-node'
 rows=[json.loads(s) for s in (evidence/'observations.jsonl').read_text().splitlines()];assert len(rows)==summary['observations'];assert all(r['passed'] for r in rows)
 cells=summary['cohorts'];index={(r['kind'],r['size'],r['profile'],r['jobs'],r['scenario'],r['system']):r for r in cells}
 for c in cells:
  sample=[r for r in rows if not r['warmup'] and all(r[k]==c[k] for k in ['kind','size','profile','jobs','scenario','system'])]
  assert len(sample)==c['samples']
  for m in ['wall_ms','cpu_ms','peak_rss_kib']:assert statistics.median(r['metrics'][m] for r in sample)==c[m]['median']
 def cell(kind,size,profile,jobs,scenario,system):return index[kind,size,profile,jobs,scenario,system]
 assets=ROOT/'public/benchmarks/build-systems/assets';assets.mkdir(parents=True,exist_ok=True)
 import matplotlib;matplotlib.use('Agg')
 import matplotlib.pyplot as plt
 plt.rcParams.update({'figure.facecolor':'#181c18','axes.facecolor':'#181c18','axes.edgecolor':'#65735c','axes.labelcolor':'#e9eddf','xtick.color':'#a5afa1','ytick.color':'#a5afa1','text.color':'#e9eddf','grid.color':'#343d32','font.family':'DejaVu Sans','font.size':11,'svg.fonttype':'none'})
 def chart(slug,title,kind,sizes,profile,jobs,scenario,metric='wall_ms',unit='ms',log=False):
  fig,ax=plt.subplots(figsize=(10.5,3.9));fig.subplots_adjust(left=.11,right=.97,top=.84,bottom=.19)
  for system in SYSTEMS:
   ys=[cell(kind,n,profile,jobs,scenario,system)[metric]['median']/(1024 if unit=='MiB' else 1) for n in sizes]
   ax.plot(sizes,ys,marker={'make':'s','ninja':'^','nift':'o'}[system],color=COLORS[system],label=NAMES[system],lw=2,markersize=6)
  ax.set_xscale('log');ax.set_xticks(sizes,labels=[f'{n:,}' for n in sizes]);ax.set_xlabel('Leaf translation units' if kind=='native' else 'Independent actions');ax.set_ylabel('Median '+('maximum-child RSS' if metric=='peak_rss_kib' else 'elapsed time')+' ('+unit+')')
  if log:ax.set_yscale('log');ax.set_ylabel(ax.get_ylabel()+' · log scale')
  else:ax.set_ylim(bottom=0)
  ax.grid(True,alpha=.8);ax.legend(loc='lower left',bbox_to_anchor=(0,1.02),ncols=3,frameon=False);ax.spines[['top','right']].set_visible(False)
  for ext in ['svg','png']:fig.savefig(assets/(slug+'.'+ext),dpi=180)
  plt.close(fig)
  tabrows=[]
  for n in sizes:
   cs=[cell(kind,n,profile,jobs,scenario,s) for s in SYSTEMS];tabrows.append([f'{n:,}',*[fmt(c[metric]['median']/(1024 if unit=='MiB' else 1)) for c in cs],str(cs[0]['samples'])])
  scale=' Both axes are logarithmic.' if log else ' Task-count spacing is logarithmic; the value axis starts at zero.'
  return f'<figure tabindex="0" role="region" aria-label="{esc(title)} chart"><img src="@path(\'public/benchmarks/build-systems/assets/{slug}.svg\')" alt="{esc(title)} — GNU Make, Ninja and Nift"><figcaption>{esc(title)}.{scale} <a href="@path(\'public/benchmarks/build-systems/assets/{slug}.svg\')">SVG</a> / <a href="@path(\'public/benchmarks/build-systems/assets/{slug}.png\')">PNG</a></figcaption></figure>'+table(title+'; '+('independent actions' if kind=='tiny' else profile)+f', j{jobs}; median {unit}', ['Corpus',*map(NAMES.get,SYSTEMS),'Samples / cell'],tabrows)
 base=f'https://github.com/nift-experiments/lab-evidence/tree/{commit}/benchmarks/build-systems/{series}'
 source=f'https://github.com/nift-experiments/build-systems/tree/{identity["suite_sha"]}'
 dag='''<div class="graph-console"><div class="console-top"><span>COMMON BUILD GRAPH</span><span class="status">ORACLE / PASS</span></div><svg class="dag" viewBox="0 0 440 290" role="img" aria-label="Input specification generates a header and source, private and shared headers feed objects, objects feed ten archives and one executable"><path d="M220 43V72M115 113V150M325 113V150M115 183V216H220V247M325 183V263H286"/><rect x="154" y="12" width="132" height="32"/><text x="168" y="33">input / schema</text><rect x="42" y="73" width="146" height="40"/><text x="55" y="91">config.h</text><text class="small" x="55" y="105">+ private / shared</text><rect x="252" y="73" width="146" height="40"/><text x="265" y="97">generated.cpp</text><path d="M220 72H115V73M220 72H325V73"/><rect x="42" y="150" width="146" height="33"/><text x="58" y="171">N objects</text><rect x="252" y="150" width="146" height="33"/><text x="264" y="171">generated.o</text><rect x="150" y="200" width="140" height="33"/><text x="163" y="222">10 archives</text><rect class="active" x="154" y="247" width="132" height="33"/><text x="174" y="269">executable</text></svg><div class="console-foot">same sources / compiler / flags / outputs<br>main.o also links directly (branch omitted)<br>three graph encodings · one executed-action oracle</div></div>'''
 body='<main id="main"><div class="hero"><div><p class="eyebrow">Build systems / same-node experiment</p><h1>The build<br>is a <em>graph.</em></h1><p class="lede">GNU Make, Ninja and Nift execute the same native project. What costs time when nothing changes—and when everything does?</p><p class="label">Four corpus sizes · two compile profiles · workers 1 / 2 / 4</p></div>'+dag+'</div><div class="system-cards"><div class="make"><b>GNU Make</b>Explicit, nonrecursive rules<br>Compiler-generated dependencies</div><div class="ninja"><b>Ninja</b>Ordinary build edges<br>Compiler dependency database</div><div class="nift"><b>Nift</b>Tracked native build actions<br>Ordering + explicit file dependencies</div></div><nav class="jump" aria-label="Report sections">'+''.join(f'<a href="#{a}">{t}</a>' for a,t in [('noop','Nothing changed'),('leaf','One file changed'),('fanout','Headers fan out'),('full','Full builds'),('tiny','Tiny actions'),('parallel','Parallel work'),('correctness','Correctness'),('resources','Resources'),('method','Evidence')])+'</nav>'
 body=body.replace('<p class="label">Four corpus sizes', '<p class="label">'+esc(identity['toolchain']['make']['version'])+' / Ninja '+esc(identity['toolchain']['ninja']['version'])+' / '+esc(identity['toolchain']['nift']['version'])+' development snapshot · <a href="#method">Frozen identities</a></p><p class="label">Four corpus sizes')
 body+=section('noop','01','Nothing changed. Everything checked.','<p>No-op includes graph loading and dependency checks. A zero action count is verified for every sample. These are warm prepared fixtures, not cold-machine boots.</p>'+chart('native-noop','Warm no-op scaling','native',[100,1000,5000,10000],'light',4,'noop',log=True))
 body+=section('leaf','02','One source edit. The whole graph in view.','<p>A byte change in one leaf source recompiles one object, updates its static archive and relinks the executable. Setup is excluded; graph traversal, these three actions and bookkeeping are included.</p>'+chart('native-leaf','One-file incremental scaling','native',[100,1000,5000,10000],'light',4,'leaf'))
 matrix=[]
 for scenario in SCENARIOS:
  cs=[cell('native',1000,'light',4,scenario,s) for s in SYSTEMS];example=next(r for r in rows if r['kind']=='native' and r['size']==1000 and r['profile']=='light' and r['jobs']==4 and r['scenario']==scenario);oracle=json.loads((evidence/example['expected_actions']).read_text());matrix.append([SCENARIOS[scenario],*[fmt(c['wall_ms']['median']) for c in cs],str(len(oracle)),str(cs[0]['samples'])])
 body+=section('fanout','03','A header edit expands the dirty set.','<p>The private header reaches one object; a module header reaches 10% of translation units; the global header reaches all native leaf objects. Generated-input changes run both generator actions and rebuild their complete consumers.</p>'+chart('native-global','Global-header rebuild scaling','native',[100,1000,5000,10000],'light',4,'global')+table('Complete native workload matrix; 1,000 light translation units, j4; median ms',['Workload',*map(NAMES.get,SYSTEMS),'Actions','Samples / cell'],matrix))
 body+=section('full','04','When the compiler owns the clock.','<p>Clean full removes outputs before timing. Clean + rebuild includes a common removal/recreation command inside timing. Native graph size is translation units + 15 actions: generators, two additional objects, ten archives and a link.</p>'+chart('native-full','Clean full build scaling','native',[100,1000,5000,10000],'light',4,'full')+'<p class="note">Large full-build cells have three measured samples. Their min–max spreads remain visible in the distributions below; no high-percentile or universal ranking claim follows from them.</p>')
 body+=section('tiny','05','Just the orchestrator and tiny actions.','<p>A separate graph contains independent deterministic FNV hash actions. It exposes loading, checking and dispatch costs; it is not C++ throughput and does not cover every DAG shape.</p>'+chart('tiny-noop','Tiny-action no-op scaling','tiny',[100,1000,10000],'light',4,'noop',log=True)+chart('tiny-full','Fully dirty tiny-action scaling','tiny',[100,1000,10000],'light',4,'full'))
 parallel=[]
 for profile,size in [('light',100),('heavy',100),('heavy',1000)]:
  for jobs in [1,2,4]:
   cs=[cell('native',size,profile,jobs,'full',s) for s in SYSTEMS];parallel.append([f'{size:,} / {profile} / j{jobs}',*[fmt(c['wall_ms']['median']) for c in cs],str(cs[0]['samples'])])
 fig,ax=plt.subplots(figsize=(10.5,3.9));fig.subplots_adjust(left=.11,right=.97,top=.84,bottom=.19)
 for si,system in enumerate(SYSTEMS):
  values=[cell('native',1000,'heavy',j,'full',system)['wall_ms']['median'] for j in [1,2,4]]
  ax.bar([i+(si-1)*.24 for i in range(3)],values,width=.22,color=COLORS[system],label=NAMES[system])
 ax.set_xticks(range(3),labels=['1 worker','2 workers','4 workers']);ax.set_ylabel('Median clean full build (ms)');ax.set_ylim(bottom=0);ax.grid(axis='y',alpha=.5);ax.set_axisbelow(True);ax.legend(loc='lower left',bbox_to_anchor=(0,1.02),ncols=3,frameon=False);ax.spines[['top','right']].set_visible(False)
 for ext in ['svg','png']:fig.savefig(assets/('parallel-heavy.'+ext),dpi=180)
 plt.close(fig)
 parallel_figure='<figure tabindex="0" role="region" aria-label="Heavy full-build worker comparison chart"><img src="@path(\'public/benchmarks/build-systems/assets/parallel-heavy.svg\')" alt="Clean full build for 1,000 heavy translation units at one, two and four workers"><figcaption>Same compiler-heavy graph, same CPU set. <a href="@path(\'public/benchmarks/build-systems/assets/parallel-heavy.svg\')">SVG</a> / <a href="@path(\'public/benchmarks/build-systems/assets/parallel-heavy.png\')">PNG</a></figcaption></figure>'
 body+=section('parallel','06','Same graph. Different worker limits.','<p>Every command uses the same allowed four logical CPUs. Worker limits are 1, 2 or 4. The heavier profile instantiates sixteen independent depth-128 templates per translation unit; its final binary behavior is unchanged. Compare workers within a fixed size/profile.</p>'+parallel_figure+table('Same chart cells: 1,000 heavy translation units; median ms',['Corpus / profile / workers',*map(NAMES.get,SYSTEMS),'Samples / cell'],parallel[-3:])+'<details><summary>100-unit light and heavy worker comparisons</summary>'+table('Additional fixed-size worker comparisons; median ms',['Corpus / profile / workers',*map(NAMES.get,SYSTEMS),'Samples / cell'],parallel[:-3])+'</details>')
 body+=section('correctness','07','Fast only counts when the work is right.',f'<p>All {len(rows):,} retained official observations, including warmups, pass the expected action-set and output-hash checks. A common wrapper records each generator, compiler, archive and link invocation. Missing, extra or duplicate work aborts the campaign.</p><div class="grid-two"><div class="fact"><h3>Same bytes, same behavior</h3><p>Generated files, objects, deterministic archives and executable hashes agree across all participants for each case. The executable verifies a known sum. Tiny outputs have an independent Python oracle.</p></div><div class="fact"><h3>Discovered dependencies checked</h3><p>Make uses -MMD -MP depfiles; Ninja imports them into its dependency database. Every discovered object include closure is audited against Nift’s explicit file inputs.</p></div></div><p class="note">Nift’s “depends” controls order, not invalidation. File dependencies include prerequisite outputs. Named Nift targets are forced; the targeted comparison starts with a dirty module for all three systems. An untimed subsequent full build verifies the final executable.</p><details><summary>Deleted / renamed input and failure boundaries</summary><p>Local certification checks unrelated files, source renames and deletions. Rename setup updates each graph and removes the affected object and obsolete depfile before timing. Make/Ninja reject a deleted source before dispatch; Nift attempts that compile and blocks downstream archive/link actions. Nonzero status and no unrelated actions are required. These failure diagnostics are not performance samples.</p></details>')
 body+=section('resources','08','Memory follows the same workload.','<p>CPU time and maximum-child RSS are retained for every timed command. Linux wait4 RSS is a child high-water measure, not summed simultaneous memory across parallel compiler processes. Wall time remains the primary metric.</p>'+chart('native-noop-rss','Warm no-op memory scaling','native',[100,1000,5000,10000],'light',4,'noop','peak_rss_kib','MiB')+chart('native-leaf-rss','One-file incremental memory scaling','native',[100,1000,5000,10000],'light',4,'leaf','peak_rss_kib','MiB'))
 distributions=[]
 for c in cells:
  distributions.append([f"{c['kind']} / {c['size']:,} / {c['profile']} / j{c['jobs']} / {SCENARIOS.get(c['scenario'],c['scenario'])}",NAMES[c['system']],str(c['samples']),fmt(c['wall_ms']['median']),fmt(c['wall_ms']['min'])+'–'+fmt(c['wall_ms']['max']),fmt(c['wall_ms']['p95']) if 'p95' in c['wall_ms'] else '—',fmt(c['wall_ms']['p99']) if 'p99' in c['wall_ms'] else '—',fmt(c['cpu_ms']['median']),fmt(c['peak_rss_kib']['median']/1024)])
 small=[c for c in cells if c['samples']<10];variable=[c for c in small if (c['wall_ms']['max']-c['wall_ms']['min'])/c['wall_ms']['median']>.25]
 if variable:body+='<p class="note">'+str(len(variable))+' of '+str(len(small))+' cells with fewer than ten samples have min–max ranges exceeding 25% of their medians. This is a descriptive variability flag, not a confidence interval. Retained distributions below identify every cell; treat these medians cautiously.</p>'
 body+='<details><summary>Every measured cell: timing distributions, CPU and memory</summary>'+table('All cells; p95 only n≥20, p99 only n≥100; no outlier deletion',['Case','System','n','Median ms','Min–max ms','p95 ms','p99 ms','CPU ms','RSS MiB'],distributions)+'</details>'
 noop_large={s:cell('native',10000,'light',4,'noop',s)['wall_ms']['median'] for s in SYSTEMS};leaf_large={s:cell('native',10000,'light',4,'leaf',s)['wall_ms']['median'] for s in SYSTEMS};heavy={s:cell('native',1000,'heavy',4,'full',s)['wall_ms']['median'] for s in SYSTEMS}
 body+=section('assessment','09','Different costs. Different strengths.', '<p>At 10,000 light translation units, '+NAMES[min(noop_large,key=noop_large.get)]+' has the lowest observed no-op median and '+NAMES[min(leaf_large,key=leaf_large.get)]+' has the lowest one-file median. At 1,000 heavy translation units / j4, '+NAMES[min(heavy,key=heavy.get)]+' has the lowest full-build median. These are descriptive cell comparisons, not significance tests or a universal ranking.</p><p>Nift’s higher-level tracked-action model is directly exercised here, including generation, ordering and targeted builds. Any dependency-checking or dispatch cost stays in the measurements. The syscall diagnostic provides a bounded lead for future core work; no optimization was made for this campaign.</p>')
 body+=section('method','10','The boundary travels with the number.',f'<p>One fresh Linode, four shared vCPUs and 8 GB RAM. Participants rotate within every round; scenario order rotates across graphs. Sources and known build state are restored, contents mutated and timestamp preconditions checked before the C timer starts. No cache flushing or cold-machine claim. Stdout/stderr are captured; default CLI status-output costs remain inside timing, while terminal painting is excluded. Every warmup and sample is preserved.</p><p>Make and Ninja edges contain the actual native inputs. Nift additionally retains its required tracked-item content and explicit file sidecars. The first trial’s extra Make/Ninja recipe-marker edges were rejected, corrected and recertified; a second trial’s one-rule-per-action Ninja encoding was also rejected in favour of shared compile/action rules. Neither provisional series is pooled here.</p><p>The matrix is bounded: every native scenario at 100/1,000 light; larger light graphs for scaling; heavy 100/1,000 for compiler and worker comparisons; independent tiny actions at 100/1,000/10,000. It is not every combination of size, profile and workers.</p><dl class="identity"><dt>Nift source</dt><dd><code>{esc(identity["nift_source_sha"])}</code> · rebuilt development snapshot</dd><dt>Suite source</dt><dd><a href="{source}"><code>{identity["suite_sha"]}</code></a></dd><dt>Toolchain</dt><dd>'+esc(' / '.join(identity['toolchain'][k]['version'] for k in ['make','ninja','nift','compiler','linker']))+f'</dd><dt>Canonical evidence</dt><dd><a href="{base}">Raw observations, definitions, action oracles, hashes and lifecycle</a></dd><dt>Reproduction</dt><dd><a href="{source}/docs/METHODOLOGY.md">Fairness contract</a> · <a href="{source}/docs/official-plan.json">Exact sample plan</a> · <a href="{source}/provenance/nift-source.json">Frozen source reconstruction</a></dd><dt>Diagnostics</dt><dd><a href="{base}/CORE-HANDOVER.md">Bounded no-op syscall handover</a>; tracing counts are diagnostic, not elapsed-time results. Nift core was not modified.</dd></dl><p class="metrics-note">Sample policy: 100 no-op; 20 modest increments; 5–10 multi-second work; three expensive large builds. All samples remain, with linear percentile interpolation at (n−1)q. Shared-CPU variability and this synthetic graph limit generalization.</p>')
 commands=[NAMES[system]+': '+shlex.join(next(r['command'] for r in rows if r['kind']=='native' and r['size']==1000 and r['profile']=='light' and r['jobs']==4 and r['scenario']=='noop' and r['system']==system)) for system in SYSTEMS]
 body+='<details><summary>Actual build invocations: 1,000 light units / j4</summary><p>Nift’s worker count is set in its generated project configuration. The common C supervisor times each command; restoration and correctness checks surround it.</p><pre tabindex="0" role="region" aria-label="Measured build commands"><code>'+esc('\n'.join(commands))+'</code></pre></details>'
 body+='</main>'
 content=ROOT/'content/benchmarks/build-systems';content.mkdir(parents=True,exist_ok=True);(content/'index.html').write_text(body+'\n')
 compact={'series':series,'evidence_commit':commit,'summary_sha256':hashlib.sha256((evidence/'summary.json').read_bytes()).hexdigest(),'suite_sha':identity['suite_sha'],'nift_sha':identity['nift_source_sha'],'observations':len(rows),'cells':cells};(content/'published.json').write_text(json.dumps(compact,separators=(',',':'))+'\n')
 print(f'Rendered {len(cells)} cells from {len(rows)} independently verified observations')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--evidence',required=True,type=Path);p.add_argument('--commit',required=True);p.add_argument('--series',required=True);a=p.parse_args();render(a.evidence,a.commit,a.series)
